"""Tenant RBAC keys shared by the portal API and the mobile users screen."""

from __future__ import annotations

PERMISSION_KEYS = {
    "dashboard",
    "liveChat",
    "training",
    "analytics",
    "settings",
    "userManagement",
    "contentManagers",
    "contentPublish",
    "activityFlow",
    "requests",
    "requestsManage",
    "requestsNotify",
    "requestsManualChat",
    "requestsSensitive",
    "comments",
    "commentsManage",
    "channelWhatsapp",
    "channelInstagram",
    "channelFacebook",
    "channelTiktok",
    "channelWeb",
}

SYSTEM_ROLE_PERMISSIONS: dict[str, dict[str, bool]] = {
    "admin": {k: True for k in PERMISSION_KEYS},
    "owner": {k: True for k in PERMISSION_KEYS},
    "platform_owner": {k: True for k in PERMISSION_KEYS},
    "operator": {
        "dashboard": True,
        "liveChat": True,
        "training": False,
        "analytics": True,
        "settings": False,
        "userManagement": False,
        "contentManagers": False,
        "contentPublish": False,
        "activityFlow": True,
        "requests": True,
        "requestsManage": True,
        "requestsNotify": True,
        "requestsManualChat": True,
        "requestsSensitive": False,
        "comments": True,
        "commentsManage": True,
        "channelWhatsapp": True,
        "channelInstagram": True,
        "channelFacebook": True,
        "channelTiktok": True,
        "channelWeb": True,
    },
    "viewer": {
        "dashboard": True,
        "liveChat": False,
        "training": False,
        "analytics": True,
        "settings": False,
        "userManagement": False,
        "contentManagers": False,
        "contentPublish": False,
        "activityFlow": True,
        "requests": False,
        "requestsManage": False,
        "requestsNotify": False,
        "requestsManualChat": False,
        "requestsSensitive": False,
        "comments": False,
        "commentsManage": False,
        "channelWhatsapp": True,
        "channelInstagram": True,
        "channelFacebook": True,
        "channelTiktok": True,
        "channelWeb": True,
    },
}
