apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linas-scheduler
  template:
    metadata:
      labels:
        app: linas-scheduler
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/mahmoudalzoughbi/linasbot-server:staging
          args: ["scheduler"]
          env:
            - name: LINAS_CONFIG_SOURCE
              value: env
            - name: LINAS_FLAG_SCHEDULER_MODE
              value: pg
            - name: LINAS_FLAG_QUEUE_BACKEND
              value: pg
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
