"""Recover must isolate generated bytecode outside hashed trees without weakening gates."""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from scripts.ha.cpython_runtime_pycache_contract import (
    PYTHON_PYCACHE_DROPIN,
    PYTHON_PYCACHE_ROOT,
    PYTHON_REPO_ROOT,
    PYTHON_RUNTIME_ROOT,
    PYTHON_VENV_ROOT,
    assert_cache_dir_contract,
    bytecode_inside,
    pycache_overlaps_immutable_root,
    restore_generated_bytecode,
)

ROOT = Path(__file__).resolve().parents[1]
HELPER = ROOT / "scripts" / "ha" / "deploy_meta_release_ha.sh"
VERIFY = ROOT / "scripts" / "ha" / "verify_meta_release_ha.sh"
GUARD = ROOT / "scripts" / "ha" / "production_mutation_guard.py"
CLUSTER_ENV = ROOT / "scripts" / "ha" / "cluster_runtime_env_contract.py"
ALEMBIC = ROOT / "alembic" / "versions" / "20260824_product_search_metadata.py"


def _helper() -> str:
    return HELPER.read_text(encoding="utf-8")


def _recover() -> str:
    source = _helper()
    return source[source.index("recover_deployment() {") : source.index("retry_distinct_reconciliation() {")]


def _dispatch() -> str:
    source = _helper()
    return source[source.index("node_dispatch() {") : source.index("reject_self_peer() {")]


def test_pycache_root_stays_outside_hashed_trees() -> None:
    pycache_overlaps_immutable_root()
    with pytest.raises(RuntimeError, match="overlaps"):
        pycache_overlaps_immutable_root(pycache_root=f"{PYTHON_RUNTIME_ROOT}/pycache")
    with pytest.raises(RuntimeError, match="overlaps"):
        pycache_overlaps_immutable_root(pycache_root="/opt/linasbot")


def test_restore_removes_only_generated_bytecode(tmp_path: Path) -> None:
    runtime = tmp_path / "runtime"
    nested = runtime / "lib" / "encodings" / "__pycache__"
    nested.mkdir(parents=True)
    (nested / "aliases.cpython-313.pyc").write_bytes(b"pyc")
    (nested / "aliases.cpython-313.pyo").write_bytes(b"pyo")
    kept = runtime / "lib" / "encodings" / "aliases.py"
    kept.write_text("ok\n", encoding="utf-8")
    removed = restore_generated_bytecode(runtime)
    assert removed >= 3
    assert kept.read_text(encoding="utf-8") == "ok\n"
    assert bytecode_inside(runtime) == []


def test_restore_leaves_non_bytecode_untracked_files(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / "services").mkdir(parents=True)
    marker = repo / "services" / "notes.txt"
    marker.write_text("keep\n", encoding="utf-8")
    cache = repo / "services" / "__pycache__"
    cache.mkdir()
    (cache / "mod.cpython-313.pyc").write_bytes(b"pyc")
    restore_generated_bytecode(repo)
    assert marker.read_text(encoding="utf-8") == "keep\n"
    assert not cache.exists()


def test_cache_dir_contract_rejects_symlink(tmp_path: Path) -> None:
    real = tmp_path / "cache"
    real.mkdir()
    os.chmod(real, 0o700)
    link = tmp_path / "link"
    link.symlink_to(real)
    with pytest.raises(RuntimeError, match="symlink"):
        assert_cache_dir_contract(link)


def test_helper_defers_pre_drain_tree_hash_then_rehashes() -> None:
    recover = _recover()
    dispatch = _dispatch()
    source = _helper()
    start = recover.index('local_runtime_cluster="$(assert_python_runtime_contract node01')
    drained = recover.index('update_recovery_journal "recovery-both-nodes-drained"')
    apply = recover.index("apply_cpython_runtime_immutability", drained)
    head = recover.index("node_assert_exact_head", apply)
    assert "deferred-until-restore" in recover[start : start + 160]
    assert apply < head
    assert "ensure-maintenance|mark-maintenance|apply-cpython-runtime-immutability|lb-attestation" in dispatch
    assert "deferred-until-restore" in dispatch
    installer = source[
        source.index("install_lb_ready_attestation() {") : source.index("assert_lb_observation_strictly_newer() {")
    ]
    assert '[ "$operation" = recover ]' in installer
    assert "tree_proof=required" in installer
    assert "tree_proof=deferred-until-restore" in installer
    assert 'assert_python_runtime_contract "$expected_node_id" "$tree_proof"' in installer
    assert 'assert_python_runtime_contract "$expected_node_id")' not in installer
    assert (
        "deferred-until-restore"
        not in source[source.index("apply_cpython_runtime_immutability() {") : source.index("require_root() {")]
    )
    assert "assert_python_runtime_tree_pristine_os" in source
    assert "PYTHON_RUNTIME_TREE_SHA256" in source
    assert source.count("canonical Python runtime tree differs from the reviewed pristine artifact") >= 1


def test_helper_cleans_runtime_venv_and_repo_bytecode_after_drain() -> None:
    source = _helper()
    restore = source[
        source.index("restore_generated_python_bytecode() {") : source.index("install_python_pycache_policy() {")
    ]
    assert '"$PYTHON_RUNTIME_ROOT"' in restore
    assert '"$REPO_DIR/venv"' in restore
    assert '"$REPO_DIR"' in restore or PYTHON_REPO_ROOT in restore
    assert "__pycache__" in restore
    assert ".pyc" in restore and ".pyo" in restore
    recover = _recover()
    drain = recover.index('node_ensure_maintenance "$tx_dir"')
    apply = recover.index('apply_cpython_runtime_immutability "$tx_dir"', drain)
    assert apply > drain
    assert 'remote_node "$peer_host" apply-cpython-runtime-immutability "$tx_dir"' in recover[apply:]


def test_helper_installs_prefix_dropin_without_changing_execstart() -> None:
    source = _helper()
    policy = source[
        source.index("install_python_pycache_policy() {") : source.index("apply_cpython_runtime_immutability() {")
    ]
    assert "PYTHON_PYCACHE_ROOT" in policy
    assert "PYTHON_PYCACHE_DROPIN" in policy
    assert "Environment=PYTHONPYCACHEPREFIX=" in policy
    assert "ExecStart=" not in policy
    assert "daemon-reload" in policy
    assert "NeedDaemonReload" in policy
    unit = source[source.index("assert_unit_file_contract() {") : source.index("assert_unit_contract() {")]
    assert PYTHON_PYCACHE_DROPIN in unit
    assert "PYTHONPYCACHEPREFIX=" in unit
    assert 'expected_exec="argv[]=$REPO_DIR/venv/bin/python main.py ;"' in unit
    verify = VERIFY.read_text(encoding="utf-8")
    assert "venv/bin/python main.py" in verify
    assert "-X pycache_prefix" not in verify


def test_env_parity_allows_only_exact_prefix_and_keeps_dotfile_ban() -> None:
    source = _helper()
    evidence = source[
        source.index("cluster_runtime_env_evidence() {") : source.index("compare_cluster_runtime_env_evidence() {")
    ]
    assert "PYTHONPYCACHEPREFIX" in evidence
    assert "PYTHON_PYCACHE_ROOT" in evidence
    guard = GUARD.read_text(encoding="utf-8")
    assert '"PYTHONPYCACHEPREFIX"' in guard
    cluster = CLUSTER_ENV.read_text(encoding="utf-8")
    assert "PYTHONPYCACHEPREFIX" not in cluster.split("FIXED_RUNTIME_VALUES", 1)[1].split("}", 1)[0]
    process = source[source.index("assert_exact_runtime_process_contract() {") : source.index("assert_ready() {")]
    assert "PYTHONPYCACHEPREFIX" in process
    assert 'live_forbidden = forbidden - {"PATH", "PYTHONPYCACHEPREFIX"}' in process or (
        'forbidden - {"PATH", "PYTHONPYCACHEPREFIX"}' in process
    )


def test_later_helper_and_lb_wait_and_journal_invariants_remain() -> None:
    recover = _recover()
    source = _helper()
    assert "commit-node01-admit" in source
    assert "assert_later_dispatch_helper" in recover
    assert "assert_public_ready_after_peer_admission" in recover
    assert "decision" in recover
    assert 'update_recovery_journal "complete"' in recover
    assert "durable deployment commit decision cannot be reversed" in source
    assert "I_UNDERSTAND_SKIPPING_GATES" not in source
    assert ALEMBIC.is_file()
    assert "nullable=True" in ALEMBIC.read_text(encoding="utf-8")


def test_fail_close_does_not_claim_both_nodes_without_peer_proof() -> None:
    recover = _recover()
    close = recover[recover.index("fail_close_recovery() {") : recover.index("trap fail_close_recovery EXIT")]
    assert ">/dev/null 2>&1" not in close
    assert "peer_rc" in close
    assert "both nodes were forced fail-closed" in close
    assert "fail-close was incomplete" in close


def test_alembic_migration_is_additive() -> None:
    text = ALEMBIC.read_text(encoding="utf-8")
    assert "op.add_column" in text
    assert "op.drop_table" not in text.split("def upgrade", 1)[1].split("def downgrade", 1)[0]
    assert "nullable=True" in text


def test_apply_rehashes_mandatory_and_does_not_exclude_bytecode() -> None:
    source = _helper()
    apply = source[source.index("apply_cpython_runtime_immutability() {") : source.index("require_root() {")]
    tree = source[
        source.index("assert_python_runtime_tree_pristine_os() {") : source.index(
            "restore_generated_python_bytecode() {"
        )
    ]
    assert "deferred-until-restore" not in apply
    assert 'assert_python_runtime_contract "$(configured_node_id)"' in apply
    assert "restore_generated_python_bytecode" in apply
    assert "install_python_pycache_policy" in apply
    assert "*.pyc" not in tree and "__pycache__" not in tree
    assert "PYTHON_RUNTIME_TREE_SHA256=e4f022d45328996d72ed818a4cecca7588b71589b8804735535ecb88a9856afc" in source


def test_commit_and_admit_paths_install_policy_before_start() -> None:
    source = _helper()
    commit = source[source.index("commit_target_deployment() {") : source.index("orchestrate() {")]
    drain = commit.index('node_ensure_maintenance "$tx_dir"')
    apply = commit.index('apply_cpython_runtime_immutability "$tx_dir"', drain)
    head = commit.index('node_assert_exact_head "$target_sha" "$tx_dir"', apply)
    assert apply < head
    assert 'remote_node "$peer_host" apply-cpython-runtime-immutability "$tx_dir"' in commit[apply:]
    start = source[
        source.index("start_admitted_target_runtime() {") : source.index("enable_admitted_target_autostart() {")
    ]
    policy = start.index("install_python_pycache_policy")
    unit = start.index("assert_unit_file_contract linasbot")
    begin = start.index("systemctl start linasbot.service")
    assert policy < unit < begin
    ensure = source[source.index("node_ensure_maintenance() {") : source.index("node_assert_runtime_drained() {")]
    capture = ensure.index("capture_service_state")
    policy_install = ensure.index("install_python_pycache_policy")
    drained = ensure.index("node_assert_runtime_drained")
    assert capture < policy_install < drained


def test_process_overlay_rejects_other_python_keys_and_keeps_argv() -> None:
    source = _helper()
    evidence = source[
        source.index("cluster_runtime_env_evidence() {") : source.index("compare_cluster_runtime_env_evidence() {")
    ]
    process = source[source.index("assert_exact_runtime_process_contract() {") : source.index("assert_ready() {")]
    assert 'if name == "PYTHONPYCACHEPREFIX":' in evidence
    assert "live PYTHONPYCACHEPREFIX is not the pinned cache root" in evidence
    assert "PYTHONPATH" in process
    assert "PYTHONHOME" in process
    assert 'expected_argv_text = "argv[]=" + " ".join(expected_argv) + " ;"' in process
    assert "main.py" in process
    assert "--queue" in process
    assert "-X pycache_prefix" not in process.split("assert_ready() {")[0]


def test_lb_later_helper_and_venv_repo_gates_stay_fail_closed() -> None:
    source = _helper()
    recover = _recover()
    assert "assert_public_ready_after_peer_admission" in recover
    assert "assert_later_dispatch_helper" in recover
    assert "canonical venv contains forbidden Python bytecode" in source
    assert "audit_untracked_runtime" in source
    assert "'*.pyc'" in source or '"*.pyc"' in source
    assert "I_UNDERSTAND_SKIPPING_GATES" not in source
    assert PYTHON_VENV_ROOT == "/opt/linasbot/venv"
    assert PYTHON_RUNTIME_ROOT == "/opt/linasbot-runtime/cpython-3.13.15"
    assert PYTHON_PYCACHE_ROOT == "/var/lib/linasbot/meta-ha/cpython-pycache"
