"""Keyword catalogs for SentimentEscalationService (LOC split)."""

from __future__ import annotations

# Anger/frustration indicators in multiple languages
ANGER_KEYWORDS = {
    "ar": [
        "غاضب",
        "زعلان",
        "مستاء",
        "منزعج",
        "متضايق",
        "مش راضي",
        "مش مبسوط",
        "مش عاجبني",
        "مش قابل",
        "مش معقول",
        "يا حرام",
        "يا خسارة",
        "فاشل",
        "سيء",
        "وحش",
        "مش كويس",
        "مش منيح",
        "بدي شكي",
        "بدي اشتكي",
        "شكوى",
        "مشكلة كبيرة",
        "ما بينفع",
        "مش نافع",
        "عصبي",
        "زعلان",
        "زعلانة",
        # Franco-Arabic frustration
        "ze3len",
        "ze3lane",
        "3asab",
        "3asabe",
        "balash",
        "blaash",
        "sho bek",
        "shu bek",
        "sho elak",
        "ma fehem",
        "ma fhem",
        "ta3ebetni",
        "ta3ebtni",
        "ze3letni",
        "3asabni",
    ],
    "en": [
        "angry",
        "mad",
        "furious",
        "upset",
        "frustrated",
        "annoyed",
        "irritated",
        "disappointed",
        "terrible",
        "awful",
        "horrible",
        "worst",
        "bad",
        "poor",
        "unacceptable",
        "ridiculous",
        "complaint",
        "complain",
        "problem",
        "issue",
        "not happy",
        "not satisfied",
        "dissatisfied",
        "fed up",
        "sick of",
    ],
    "fr": [
        "fâché",
        "en colère",
        "furieux",
        "mécontent",
        "frustré",
        "agacé",
        "irrité",
        "déçu",
        "terrible",
        "horrible",
        "mauvais",
        "pire",
        "inacceptable",
        "ridicule",
        "plainte",
        "problème",
        "pas content",
        "pas satisfait",
        "insatisfait",
    ],
}

# Demanding human operator keywords (Arabic + Franco-Arabic / Lebanese)
HUMAN_REQUEST_KEYWORDS = {
    "ar": [
        "بدي احكي مع حدا",
        "بدي موظف",
        "بدي شخص",
        "بدي انسان",
        "وديني على موظف",
        "حولني على موظف",
        "بدي مدير",
        "بدي مسؤول",
        "مش بدي بوت",
        "مش بدي روبوت",
        "بدي حدا بشري",
        "بدي حدا حقيقي",
        "ما بدي معك",
        "بدي غيرك",
        "بدي حدا تاني",
        "بدي حدا يساعدني",
        "موظف خدمة عملاء",
        "خدمة العملاء",
        "بدي اشتكي",
        "بدي شكوى",
        "بدي احكي مع موظف",
        "بدي احكي مع انسان",
        "بدي احكي مع حدا بشري",
        "عايز اكلم حد",
        "عايز اتكلم مع حد",
        "عايز موظف",
        "عايز انسان",
        "اريد موظف",
        "اريد انسان",
        "اريد التحدث مع موظف",
        "اريد التحدث مع انسان",
        "بدّي موظف",
        "بدّي إنسان",
        "بدّي احكي مع موظف",
        "بدّي احكي مع انسان",
        "حابب احكي مع موظف",
        "نفسي احكي مع حدا",
        "لو سمحت بدي موظف",
        "حولوني على موظف",
        "وصلوني لموظف",
        "في حدا يحكي معي",
        # Franco-Arabic / Lebanese colloquial
        "bede mwzaf",
        "bede mwazzaf",
        "bede hada ye7kine",
        "bede hada ye7ke",
        "hada ye7ke ma3e",
        "hada ye7kine",
        "bede hada ye7ke ma3e",
        "ye7ke ma3e",
        "hada ye7ke ma3i",
        "bede hada ehke ma3o",
        "bede hada y7kine",
        "hada y7ke ma3e",
        "bede hada y7ke ma3e",
        "i need human",
        "need human",
        "want human",
        "bede human",
    ],
    "en": [
        "speak to someone",
        "talk to someone",
        "human",
        "real person",
        "transfer me",
        "connect me",
        "operator",
        "agent",
        "representative",
        "customer service",
        "manager",
        "supervisor",
        "not a bot",
        "real human",
        "actual person",
        "someone else",
        "help me",
        "complaint",
        "complain",
        "escalate",
        "live agent",
        "human agent",
        "speak to an agent",
        "talk to an agent",
        "connect me to an agent",
        "i need human",
        "need human",
        "want human",
    ],
    "franco": [
        "bede mwzaf",
        "bede mwazzaf",
        "bede hada ye7kine",
        "bede hada ye7ke",
        "hada ye7ke ma3e",
        "hada ye7kine",
        "bede hada ye7ke ma3e",
        "ye7ke ma3e",
        "hada ye7ke ma3i",
        "bede hada ehke ma3o",
        "bede hada y7kine",
        "hada y7ke ma3e",
        "bede hada y7ke ma3e",
        "i need human",
        "need human",
        "want human",
        "bede human",
    ],
    "fr": [
        "parler à quelqu'un",
        "personne réelle",
        "humain",
        "opérateur",
        "agent",
        "représentant",
        "service client",
        "responsable",
        "pas un bot",
        "vraie personne",
        "quelqu'un d'autre",
        "plainte",
        "se plaindre",
        "agent humain",
        "parler à un agent",
    ],
}

# Confusion/frustration indicators (triggers escalation when combined)
CONFUSION_KEYWORDS = {
    "ar": [
        "مش فاهم",
        "ما فهمت",
        "مش واضح",
        "مش مفهوم",
        "معقد",
        "صعب",
        "مش عارف",
        "ما بعرف",
        "مش قادر",
        "تعبتني",
        "كتير معقد",
        "مش بسيط",
        "مش سهل",
        "محتار",
        "ضايع",
        "مش عم بفهم",
        "ما عم بفهم",
        "شو يعني",
        "كيف يعني",
        # Franco-Arabic
        "ma fehem",
        "ma fhem",
        "mish fahm",
        "shu 3am te2oul",
        "mish wade7",
    ],
    "en": [
        "don't understand",
        "not clear",
        "confusing",
        "confused",
        "complicated",
        "difficult",
        "hard",
        "can't figure",
        "makes no sense",
        "doesn't make sense",
        "what do you mean",
        "i don't get it",
        "lost",
        "stuck",
        "frustrated",
    ],
    "fr": [
        "ne comprends pas",
        "pas clair",
        "confus",
        "compliqué",
        "difficile",
        "je ne comprends pas",
        "qu'est-ce que",
        "ça n'a pas de sens",
        "perdu",
        "bloqué",
    ],
}

CLARIFICATION_KEYWORDS = {
    "ar": [
        "وضحلي",
        "فسرلي",
        "شرحلي",
        "اشرح",
        "فسر",
        "وضح",
        "شو قصدك",
        "شو يعني",
        "شو المقصود",
        "مش واضح",
        "ما فهمت",
        "مش فاهم",
        "وضح سؤالك",
    ],
    "en": [
        "explain",
        "clarify",
        "what do you mean",
        "not clear",
        "i don't understand",
        "i dont understand",
        "can you explain",
    ],
    "fr": ["explique", "clarifie", "je ne comprends pas", "pas clair", "qu'est-ce que tu veux dire"],
}

# Profanity/offensive language (mild detection)
OFFENSIVE_KEYWORDS = {
    "ar": [
        "غبي",
        "احمق",
        "أحمق",
        "تافه",
        "سخيف",
        "وسخ",
        "قذر",
        "حقير",
        "خرا",
        "خرة",
        "زبالة",
        "ابن الكلب",
        "يا كلب",
        "تفو",
        "يلعن",
        "لعنة",
        "عير",
        "عيركم",
        "بهيم",
        "بهائم",
        "ما فهم",
        "مفهم",
    ],
    "en": [
        "stupid",
        "idiot",
        "dumb",
        "useless",
        "garbage",
        "trash",
        "crap",
        "suck",
        "sucks",
        "moron",
        "fool",
        "asshole",
        "dick",
        "shit",
        "bullshit",
        "damn you",
        "screw you",
        "fuck",
        "fucking",
        "piece of shit",
        "motherfucker",
        "bastard",
        "sucker",
    ],
    "fr": [
        "stupide",
        "idiot",
        "nul",
        "débile",
        "pourri",
        "con",
        "connard",
        "merde",
        "putain",
        "enculé",
        "salope",
        "crétin",
        "imbécile",
        "dégage",
        "va te faire",
        "ferme ta gueule",
        "ta gueule",
    ],
    "franco": [
        "5ara",
        "khara",
        "kol hawa",
        "kell hawa",
        "koul hawa",
        "kol 5ara",
        "kol khara",
        "zbele",
        "zbale",
        "ya kalb",
        "ibn kalb",
        "tfou",
        "yl3an",
        "3alek",
        "3layk",
        "3alayk",
        "ahbal",
        "a7bal",
        "hmar",
        "7mar",
        "kalb",
        "zbaleh",
        "zbeleh",
        "manyk",
        "emak",
        "e5tak",
        "e5t",
        "bhim",
        "bala fhem",
        "ma fhem",
        "eyre",
        "eyreh",
        "eyre fikon",
        "eyreh fikon",
        "m2yra",
        "ma3e",
        "kiss emak",
        "kiss e5tak",
        "bala fhem",
        "mafhem",
        "le heak",
        "le heak sar",
        "le7ak",
        "le7e2",
        "sir 3al",
        "sir 3alek",
        "sir 3layk",
    ],
}

# Urgency indicators
URGENCY_KEYWORDS = {
    "ar": [
        "عاجل",
        "ضروري",
        "مستعجل",
        "سريع",
        "بسرعة",
        "حالاً",
        "فوراً",
        "الآن",
        "هلق",
        "دلوقتي",
        "مهم",
        "مهم جداً",
        "طارئ",
        "emergency",
        "urgent",
    ],
    "en": [
        "urgent",
        "emergency",
        "asap",
        "immediately",
        "right now",
        "quickly",
        "fast",
        "important",
        "critical",
        "serious",
    ],
    "fr": [
        "urgent",
        "urgence",
        "immédiatement",
        "tout de suite",
        "rapidement",
        "vite",
        "important",
        "critique",
        "sérieux",
    ],
}
