"""English in-app welcome lines. Each template must include {hi}."""

from __future__ import annotations

WELCOME_EN: tuple[str, ...] = (
    "{hi} 👋 Welcome back — what do you want to do today?",
    "{hi} 👋 Hope work is treating you well. What should we tackle?",
    "{hi} 👋 Good to see you. How’s the day going so far?",
    "{hi} 👋 I’m here — what’s on your mind today?",
    "{hi} 👋 Hope everything’s going well. Where should we start?",
    "{hi} 👋 Welcome back. Want to knock something off the list?",
    "{hi} 👋 How’s work treating you? I’m ready when you are.",
    "{hi} 👋 Nice to have you here. What would make today easier?",
    "{hi} 👋 Hope you’re doing well. What can I help with?",
    "{hi} 👋 Fresh chat, same me. What are we doing today?",
    "{hi} 👋 Take a breath — then tell me what you need.",
    "{hi} 👋 Welcome back. Shall we make a little progress?",
    "{hi} 👋 How’s everything on your side? I’m all ears.",
    "{hi} 👋 If the day’s been busy, we can keep this simple. What’s first?",
    "{hi} 👋 Glad you’re here. What should we look at?",
    "{hi} 👋 Hope the day’s been kind. What do you want to get done?",
    "{hi} 👋 I’m around. Want to talk something through?",
    "{hi} 👋 Welcome back — no rush. What would you like to do?",
    "{hi} 👋 How’s work going? Point me at whatever’s useful.",
    "{hi} 👋 Good timing. What can I take off your plate?",
    "{hi} 👋 Hope you’re well. What’s the plan for this chat?",
    "{hi} 👋 New page, same friendly face. Where do we begin?",
    "{hi} 👋 If you need a sounding board, I’m here. What’s up?",
    "{hi} 👋 Welcome back. Anything you want to sort out today?",
    "{hi} 👋 How are things going? Tell me how I can help.",
    "{hi} 👋 Coffee optional. Help is very much on the menu. What do you need?",
    "{hi} 👋 Hope everything’s running smoothly. What should we do?",
    "{hi} 👋 I’m glad you’re back. What’s the one thing we should handle?",
    "{hi} 👋 Light lift or a bigger task — you pick. What’s today about?",
    "{hi} 👋 How’s the workload? We can start small if you like.",
    "{hi} 👋 Welcome in. What would you like to work on?",
    "{hi} 👋 Hope you’re having a decent day. How can I help?",
    "{hi} 👋 Ready when you are. What’s the first thing on your mind?",
    "{hi} 👋 Good to see you again. Want to get something done together?",
    "{hi} 👋 If work’s been a lot, we can take it one step. What’s first?",
    "{hi} 👋 Welcome back. What’s useful to talk about right now?",
    "{hi} 👋 How are you holding up? I’m here to help.",
    "{hi} 👋 Let’s make this chat count. What do you want to do?",
    "{hi} 👋 Hope things are going well at work. What should we look into?",
    "{hi} 👋 I’ve got time. What’s on yours?",
    "{hi} 👋 Welcome back — tell me how I can make today a bit easier.",
    "{hi} 👋 No pressure, just a hello. What would you like to do?",
    "{hi} 👋 How’s business treating you? I’m ready to help.",
    "{hi} 👋 Nice to be back with you. What’s the move today?",
    "{hi} 👋 Hope you’re doing alright. Where should we start?",
    "{hi} 👋 A fresh chat for whatever you need. What’s first?",
    "{hi} 👋 If you’ve got a question or a task, I’m in. What’s up?",
    "{hi} 👋 Welcome back. Want to check something, or just think out loud?",
    "{hi} 👋 How’s the day unfolding? Point me in the right direction.",
    "{hi} 👋 Glad you’re here. What can we do for you today?",
)
