"""French in-app welcome lines (vous, friendly). Each template must include {hi}."""

from __future__ import annotations

WELCOME_FR: tuple[str, ...] = (
    "{hi} 👋 Bon retour — que voulez-vous faire aujourd’hui ?",
    "{hi} 👋 J’espère que le travail vous traite bien. On s’occupe de quoi ?",
    "{hi} 👋 Content de vous voir. Comment se passe la journée ?",
    "{hi} 👋 Je suis là — qu’est-ce qui vous passe par la tête ?",
    "{hi} 👋 J’espère que tout va bien. Par où commencer ?",
    "{hi} 👋 Bon retour. On raye quelque chose de la liste ?",
    "{hi} 👋 Comment va le travail ? Je suis prêt quand vous l’êtes.",
    "{hi} 👋 Ravi de vous avoir ici. Qu’est-ce qui rendrait la journée plus simple ?",
    "{hi} 👋 J’espère que vous allez bien. Comment puis-je aider ?",
    "{hi} 👋 Nouveau chat, même moi. On fait quoi aujourd’hui ?",
    "{hi} 👋 Respirez un peu — puis dites-moi ce dont vous avez besoin.",
    "{hi} 👋 Bon retour. On avance un petit pas ?",
    "{hi} 👋 Comment ça va de votre côté ? Je vous écoute.",
    "{hi} 👋 Si la journée est chargée, on peut rester simple. Quoi en premier ?",
    "{hi} 👋 Content que vous soyez là. On regarde quoi ?",
    "{hi} 👋 J’espère que la journée est douce. Que voulez-vous avancer ?",
    "{hi} 👋 Je suis dans le coin. On en discute ?",
    "{hi} 👋 Bon retour — pas de pressé. Que souhaitez-vous faire ?",
    "{hi} 👋 Comment va le boulot ? Orientez-moi vers ce qui est utile.",
    "{hi} 👋 Bon timing. Qu’est-ce que je peux vous enlever des épaules ?",
    "{hi} 👋 J’espère que vous allez bien. Quel est le plan de ce chat ?",
    "{hi} 👋 Page blanche, même visage amical. On commence où ?",
    "{hi} 👋 Si vous voulez un avis, je suis là. Quoi de neuf ?",
    "{hi} 👋 Bon retour. Quelque chose à régler aujourd’hui ?",
    "{hi} 👋 Comment ça se passe ? Dites-moi comment aider.",
    "{hi} 👋 Le café est optionnel. L’aide est au menu. De quoi avez-vous besoin ?",
    "{hi} 👋 J’espère que tout roule. Que fait-on ?",
    "{hi} 👋 Content de vous revoir. Quelle est la chose à traiter ?",
    "{hi} 👋 Petite tâche ou plus costaud — à vous. C’est quoi aujourd’hui ?",
    "{hi} 👋 Comment est la charge ? On peut commencer petit si vous voulez.",
    "{hi} 👋 Bienvenue. Sur quoi aimeriez-vous travailler ?",
    "{hi} 👋 J’espère que vous avez une journée correcte. Comment aider ?",
    "{hi} 👋 Prêt quand vous l’êtes. Qu’est-ce qui vient en premier ?",
    "{hi} 👋 Content de vous revoir. On avance quelque chose ensemble ?",
    "{hi} 👋 Si le travail pèse, on y va étape par étape. Quoi d’abord ?",
    "{hi} 👋 Bon retour. De quoi est-il utile de parler maintenant ?",
    "{hi} 👋 Comment vous tenez-vous ? Je suis là pour aider.",
    "{hi} 👋 Faisons compter ce chat. Que voulez-vous faire ?",
    "{hi} 👋 J’espère que le travail se passe bien. On regarde quoi ?",
    "{hi} 👋 J’ai un moment. Et vous, qu’avez-vous ?",
    "{hi} 👋 Bon retour — dites-moi comment rendre la journée un peu plus légère.",
    "{hi} 👋 Sans pression, juste un bonjour. Que souhaitez-vous faire ?",
    "{hi} 👋 Comment va le business ? Je suis prêt à aider.",
    "{hi} 👋 Content d’être de nouveau avec vous. C’est quoi le plan du jour ?",
    "{hi} 👋 J’espère que vous allez bien. On commence où ?",
    "{hi} 👋 Un chat tout neuf pour ce dont vous avez besoin. Quoi d’abord ?",
    "{hi} 👋 Question ou tâche, je suis partant. Quoi de neuf ?",
    "{hi} 👋 Bon retour. On vérifie quelque chose, ou on réfléchit à voix haute ?",
    "{hi} 👋 Comment se déroule la journée ? Pointez-moi dans la bonne direction.",
    "{hi} 👋 Content que vous soyez là. Que peut-on faire pour vous aujourd’hui ?",
)
