/**
 * Live Chat inbox design + operator actions (no device required).
 * Run: node --test mobile/linas-ai/tests/*.test.mjs
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = (...p) => join(root, 'src', ...p);
const read = (...p) => readFileSync(src(...p), 'utf8');

test('inbox is a flat list with channel chips and no section headers', () => {
  const hook = read('features/livechat/useLiveChatInbox.ts');
  const inbox = read('features/livechat/LiveChatInbox.tsx');
  const screen = read('features/livechat/LiveChatScreen.tsx');
  const human = read('features/livechat/InboxHumanHeaderButton.tsx');
  assert.doesNotMatch(hook, /Waiting for human|With operator|AI handling/);
  assert.doesNotMatch(inbox, /section\.title|kind === 'header'/);
  assert.match(inbox, /InboxSearchBar/);
  assert.match(inbox, /InboxChannelChips/);
  assert.match(inbox, /allowedChannels/);
  assert.match(inbox, /matchesAllowedChannels/);
  assert.doesNotMatch(inbox, /InboxFilterPills/);
  assert.match(screen, /InboxHumanHeaderButton/);
  assert.match(screen, /useLiveChatAccess/);
  assert.match(screen, /headerRight/);
  assert.match(human, /feather\('user'\)/);
  assert.match(hook, /waitingCount/);
  assert.match(hook, /setFilter/);
  assert.match(inbox, /<FlatList/);
  assert.match(inbox, /data=\{visibleChats\}/);
  assert.match(inbox, /styles\.toolbar/);
  assert.match(inbox, /styles\.listWrap/);
  assert.doesNotMatch(inbox, /if \(loading\) \{/);
  assert.match(inbox, /ScreenSkeleton variant="inbox"/);
  assert.doesNotMatch(inbox, /variant="screen"/);
  const chips = read('features/livechat/InboxChannelChips.tsx');
  assert.match(chips, /flexGrow:\s*0/);
  assert.match(chips, /height:\s*CHIP_ROW_H/);
  assert.match(inbox, /minHeight:\s*0/);
  assert.match(inbox, /ConversationRow/);
  assert.match(chips, /reqFilterAll/);
  assert.match(chips, /styles\.allLabel/);
  assert.match(chips, /chip\.id === 'all'/);
  assert.match(chips, /PlatformChannelIcon/);
});

test('row layout is icon / name+preview / time+badge+assignee', () => {
  const row = read('features/livechat/ConversationRow.tsx');
  const divider = read('features/livechat/InboxRowDivider.tsx');
  const inbox = read('features/livechat/LiveChatInbox.tsx');
  assert.match(row, /styles\.middle/);
  assert.match(row, /styles\.meta/);
  assert.match(row, /badgeSpacer/);
  assert.match(row, /assigneeLabel\(item\)/);
  assert.match(row, /chatChannel\(item\)/);
  assert.match(row, /InboxRowDivider/);
  assert.doesNotMatch(row, /borderBottomWidth/);
  assert.match(divider, /EDGE_INSET/);
  assert.match(divider, /fadeIn/);
  assert.match(inbox, /showDivider=\{index < visibleChats\.length - 1\}/);
  assert.doesNotMatch(row, /chatAvatarLetter/);
});

test('thread restores WhatsApp handoff, assign, and composer', () => {
  const thread = read('features/livechat/LiveChatThread.tsx');
  const composer = read('features/livechat/LiveChatComposer.tsx');
  const api = read('features/livechat/liveChatApi.ts');
  const hook = read('features/livechat/useLiveChatThread.ts');
  assert.match(thread, /LiveChatComposer/);
  assert.match(thread, /onSendMedia/);
  assert.match(thread, /allowOperatorMedia/);
  assert.match(thread, /chatChannel\(chat\)/);
  assert.match(thread, /tiktok/);
  assert.match(composer, /onSendMedia/);
  assert.match(composer, /onSendMedia/);
  assert.match(composer, /useSafeAreaInsets/);
  assert.match(composer, /Math.max\(insets.bottom, 12\)/);
  assert.match(thread, /insets.top \+ 68/);
  assert.match(composer, /feather\('image'\)/);
  assert.match(composer, /feather\('mic'\)/);
  assert.match(read('features/livechat/LiveChatThreadActions.tsx'), /Assign to AI/);
  assert.match(thread, /LiveChatAssignSheet/);
  assert.match(thread, /thread\.takeover\(staff\.id\)/);
  assert.match(api, /assignToUserId/);
  assert.match(hook, /takeoverConversation\(chat!, assignToUserId\)/);
  assert.match(hook, /dispatchOperatorSend/);
  assert.match(hook, /mergeThreadMessages/);
  assert.match(hook, /applyRealtime/);
  assert.match(hook, /requestIdRef/);
  assert.doesNotMatch(hook, /sendingRef/);
  assert.match(hook, /audio_url: type === 'voice'/);
  assert.doesNotMatch(hook, /sendText:[\s\S]*setBusy\(true\)/);
  assert.match(thread, /busy=\{thread\.busy\}/);
  assert.doesNotMatch(thread, /thread\.busy \|\| \(thread\.loading && !thread\.messages\.length\)/);
  assert.match(thread, /useLiveChatOperatorPresence/);
  assert.match(hook, /claimOnOpen/);
  assert.match(hook, /previewMessagesFromInbox/);
  assert.doesNotMatch(hook, /days:\s*1/);
  assert.doesNotMatch(thread, /thread\.sending/);
  assert.doesNotMatch(hook, /WhatsApp-only for now/);
  assert.match(hook, /retryFailedSend/);
  assert.match(hook, /idempotencyKey/);
  assert.match(hook, /delivery_status: 'sending'/);
  assert.doesNotMatch(hook, /prev.filter\(\(msg\) => \(msg.client_send_id \|\| msg.message_id\) !== dropped\)/);
  assert.match(thread, /thread\.retryFailedSend/);
  const bubble = read('features/livechat/LiveChatMessageBubble.tsx');
  const media = read('features/livechat/LiveChatMedia.tsx');
  assert.match(bubble, /LiveChatVoicePlay/);
  assert.match(bubble, /tapToRetry/);
  assert.match(bubble, /delivery_status/);
  assert.doesNotMatch(bubble, /🎤 \{body\}/);
  assert.match(media, /useAudioPlayer/);
  assert.match(media, /Play voice message/);
  const events = read('features/livechat/useLiveChatEvents.ts');
  const screen = read('features/livechat/LiveChatScreen.tsx');
  assert.match(events, /AppState/);
  assert.match(screen, /message_status/);
  assert.match(api, /idempotencyKey/);
});
