"""Conversation router pattern catalogs (LOC split from conversation_router)."""

from __future__ import annotations

import re

# --- Human handover intent (meaning-based; common phrases) ---
HUMAN_REQUEST_PATTERNS = [
    # Arabic
    r"بدي\s*(?:أحكي|أتكلم|أتكلم)\s*(?:مع|ل)",
    r"بدي\s*(?:موظف|موظفة|حدا|حد)\s*(?:يحكي|يتواصل|يرد)\s*معي",
    r"خليني\s*(?:احكي|اتواصل)\s*مع\s*(?:حد|موظف|موظفة)",
    r"بدي\s*الدعم\s*البشري",
    r"حوّلني\s*(?:لموظف|للموظف|لبشر|لإنسان)",
    r"حد\s*(?:يحكي|يتكلم)\s*معي",
    r"موظف",
    r"موظفة",
    r"إنسان",
    r"شخص\s*حقيقي",
    r"واحد\s*(?:منكم|منكن)",
    r"بدي\s*حد",
    r"حابب\s*أحكي\s*مع",
    r"بدي\s*احكي\s*مع",
    r"بدّي\s*احكي\s*مع",
    r"بدي\s*أحكي\s*مع",
    r"احكي\s*مع\s*حدا",
    r"بدي\s*خدمة\s*العملاء",
    r"ما\s*بدي\s*بوت",
    r"ممكن\s*(?:حد|واحد)\s*(?:يحكي|يتكلم)",
    r"أريد\s*التحدث\s*مع",
    r"أريد\s*موظف",
    r"أريد\s*(?:إنسان|موظفة)",
    # Franco / Arabizi
    r"bade\s*(?:ehke|a7ke)\s*ma[3a]?\s*(?:hada|7ada|human|agent)",
    r"baddi\s*(?:hada|7ada)\s*(?:y7ke|ye7ke)\s*ma3e",
    r"(?:7awelni|hawelni)\s*(?:la|lal)\s*(?:hada|7ada|human|agent|mowazaf)",
    r"bade\s*(?:mowazaf|mwazzaf|employee|agent)",
    r"ma\s*bade\s*bot",
    r"bade\s*customer\s*service",
    r"khallini\s*ehke\s*ma3\s*(?:hada|agent|employee)",
    # English
    r"speak\s*(?:to|with)\s*(?:a\s*)?(?:human|person|agent|representative|employee)",
    r"i\s*want\s*to\s*speak\s*(?:to|with)\s*(?:someone|a\s*human|an?\s*agent)",
    r"can\s*i\s*speak\s*(?:to|with)\s*(?:someone|an?\s*agent|a\s*human)",
    r"i\s*need\s*(?:help\s*from\s*)?(?:a\s*)?(?:human|agent|representative|person)",
    r"no\s*bot",
    r"not\s*(?:a\s*)?bot",
    r"live\s*agent",
    r"talk\s*(?:to|with)\s*(?:a\s*)?(?:human|person|agent|representative)",
    r"customer\s*service",
    r"connect\s*me\s*(?:to|with)",
    r"transfer\s*me\s*(?:to|with)",
    r"real\s*person",
    r"human\s*agent",
    # French
    r"parler\s*(?:à|avec)\s*(?:un\s*)?(?:humain|employé|agent|personne)",
    r"je\s*veux\s*parler\s*(?:à|avec)\s*(?:un\s*)?(?:humain|agent|employé)",
    r"pouvez[-\s]*vous\s*me\s*passer\s*(?:un\s*)?(?:agent|humain|employé)",
    r"pas\s*de\s*bot",
    r"service\s*client",
    r"vraie\s*personne",
    r"agent\s*humain",
]
HUMAN_REQUEST_RE = re.compile("|".join(f"({p})" for p in HUMAN_REQUEST_PATTERNS), re.IGNORECASE | re.UNICODE)

# Simple keywords (fallback when regex misses)
HUMAN_REQUEST_KEYWORDS = [
    "human",
    "موظف",
    "موظفة",
    "حد يحكي",
    "بدي حد",
    "واحد منكم",
    "شخص حقيقي",
    # Do not use bare English "person" — matches "personal care tips" falsely.
    "representative",
    "employee",
    "customer service",
    "service client",
    "بدي حدا",
    "بدي انسان",
    "حوّلني",
    "حولني",
    "تحويل لموظف",
    "بدي احكي مع حدا",
    "بدّي احكي مع حدا",
    "احكي مع حدا",
    "مع حدا",
    "بدي احكي مع شخص",
    "احكي مع شخص",
    "bade hada",
    "baddi hada",
    "bade a7ke",
    "ehke ma3",
    "hawelni",
    "7awelni",
    "ما بدي بوت",
    "live agent",
    "no bot",
    "not a bot",
    "pas de bot",
    "human agent",
    "real person",
]

# --- Gender answer patterns ---
GENDER_MALE_PATTERNS = [
    r"^(?:ذكر|male|homme|man|men|boy|شب|شاب|رجل|رجال|زلمة|أنا\s*شب|أنا\s*شاب|أنا\s*زلمة|انا\s*شب|انا\s*زلمة|ana\s*zalame|ana\s*zalameh|ana\s*shab|ana\s*rajol|i'm\s*male|i\s*am\s*male|je\s*suis\s*homme)",
    r"\b(?:ذكر|male|homme|man|men|boy|m|شب|شاب|رجل|رجال|زلمة|zalame|zalameh|zalmeh|zalme|shab|rajol|zakar|manly)\b",
]
GENDER_FEMALE_PATTERNS = [
    r"^(?:أنثى|female|femme|woman|women|girl|صبية|بنت|امرأة|نساء|مرة|مرا|أنا\s*صبية|أنا\s*بنت|أنا\s*مرة|انا\s*بنت|انا\s*مرة|ana\s*(?:bent|binit)|ana\s*mara|ana\s*sabeye|i'm\s*female|i\s*am\s*female|je\s*suis\s*femme)",
    r"\b(?:أنثى|female|femme|woman|women|girl|f|صبية|بنت|مرة|مرا|mara|mra|bent|binit|sabeye|sabya|onsa)\b",
]

# --- Greeting-only patterns (no service/pricing/booking) ---
GREETING_ONLY_PATTERNS = [
    r"^(?:مرحبا|مرحبا|marhaba|هلا|أهلا|سلام|السلام\s*عليكم)",
    r"^(?:hello|hi|hey|good\s*morning|good\s*evening)",
    r"^(?:bonjour|salut|coucou)",
    r"^(?:اهلين|أهلين|يا\s*هلا|هلا\s*فيك)",
    r"^(?:bonsoir|bonne\s*soirée)",
    r"^(?:mar7aba|ahla)",
]
GREETING_RE = re.compile("|".join(f"({p})" for p in GREETING_ONLY_PATTERNS), re.IGNORECASE | re.UNICODE)

# Messages that are ONLY greeting (short, no other content)
SERVICE_PRICING_BOOKING_KEYWORDS = [
    "سعر",
    "اسعار",
    "كم",
    "قديش",
    "أديش",
    "price",
    "cost",
    "pricing",
    "combien",
    "prix",
    "ليزر",
    "شعر",
    "وشم",
    "تاتو",
    "laser",
    "hair",
    "tattoo",
    "حجز",
    "booking",
    "reservation",
    "خدمة",
    "service",
    "علاج",
    "treatment",
    "جلسة",
    "session",
    "موعد",
    "appointment",
    "book",
    "rdv",
    "rendez-vous",
    "épilation",
    "epilation",
    "détatouage",
    "whitening",
    "blanchiment",
    "co2",
    "dpl",
    "sa3er",
    "as3ar",
    "2adde",
    "2adesh",
    "hajz",
    "7ajz",
    "tatouage",
    "tarif",
]

# --- Vague messages that need clarification ---
VAGUE_CLARIFICATION_PATTERNS = [
    r"^شو\s*الأسعار\s*[؟?]?$",
    r"^كم\s*السعر\s*[؟?]?$",
    r"^بدي\s*أعرف\s*[؟?]?$",
    r"^بدي\s*استفسر\s*[؟?]?$",
    r"^بدي\s*أحجز\s*[؟?]?$",
    r"^prices?\s*[?]?$",
    r"^how\s*much\s*[?]?$",
    r"^بدي\s*معلومات\s*[؟?]?$",
    r"^بدي\s*تفاصيل\s*[؟?]?$",
    r"^حابب\s*استفسر\s*[؟?]?$",
    r"^عندي\s*سؤال\s*[؟?]?$",
    r"^ممكن\s*سؤال\s*[؟?]?$",
    r"^info\s*[?]?$",
    r"^information\s*[?]?$",
    r"^i\s*have\s*a\s*question\s*[?]?$",
    r"^book\s*[?]?$",
    r"^booking\s*[?]?$",
    r"^reservation\s*[?]?$",
    r"^je\s*veux\s*des\s*infos\s*[?]?$",
    r"^prix\s*[?]?$",
    r"^tarif\s*[?]?$",
    r"^rdv\s*[?]?$",
    r"^bade\s*es2al\s*[?]?$",
    r"^kam\s*el\s*sa3er\s*[?]?$",
]
VAGUE_RE = re.compile("|".join(f"({p})" for p in VAGUE_CLARIFICATION_PATTERNS), re.IGNORECASE | re.UNICODE)

# --- Service-related (needs gender when unknown) ---
SERVICE_INTENT_KEYWORDS = [
    "ليزر",
    "شعر",
    "وشم",
    "تاتو",
    "laser",
    "hair",
    "tattoo",
    "جلسة",
    "session",
    "علاج",
    "treatment",
    "خدمة",
    "service",
    "سعر",
    "اسعار",
    "price",
    "pricing",
    "إزالة",
    "removal",
    "تبييض",
    "whitening",
    "حب شباب",
    "acne",
    "موعد",
    "appointment",
    "حجز",
    "booking",
    "reservation",
    "book",
    "co2",
    "dpl",
    "botox",
    "filler",
    "skin",
    "tatouage",
    "épilation",
    "epilation",
    "blanchiment",
    "sa3er",
    "as3ar",
    "hajz",
    "mou3ed",
    "3elaj",
]

TATTOO_KEYWORDS = ["وشم", "تاتو", "tattoo", "tatouage", "tatou"]
BOOKING_OR_PRICE_KEYWORDS = [
    "سعر",
    "اسعار",
    "price",
    "pricing",
    "cost",
    "prix",
    "حجز",
    "booking",
    "book",
    "reservation",
    "موعد",
    "ميعاد",
    "appointment",
    "date",
    "time",
    "session",
    "جلسة",
    "as3ar",
    "sa3er",
    "2adde",
    "2adesh",
    "hajz",
    "rdv",
    "rendez-vous",
    "tarif",
]

