"""Persistent storage paths and migration."""

from __future__ import annotations

from storage.persistent_storage import (
    APP_SETTINGS_FILE,
    APPOINTMENT_FINGERPRINTS_FILE,
    CONTENT_DIR,
    DAILY_TEMPLATE_DISPATCH_STATE_FILE,
    DRY_RUN_MESSAGES_FILE,
    KNOWLEDGE_BASE_FILE,
    KNOWLEDGE_FILES_DIR,
    MESSAGE_PREVIEW_QUEUE_FILE,
    MESSAGE_QUEUE_FILE,
    MESSAGE_TEMPLATES_FILE,
    MESSAGE_TEMPLATES_LOCK_FILE,
    PRICE_FILES_DIR,
    PRICE_LIST_FILE,
    QA_DATABASE_FILE,
    QA_DIR,
    QA_PAIRS_FILE,
    SCHEDULED_MESSAGES_FILE,
    SENT_SMART_MESSAGES_FILE,
    SERVICE_TEMPLATE_MAPPING_FILE,
    SETTINGS_DIR,
    SMART_MESSAGING_DIR,
    STYLE_FILES_DIR,
    STYLE_GUIDE_FILE,
    TEMPLATE_ACTIVATION_STATUS_FILE,
    ensure_dirs,
    get_content_path,
    get_data_root,
    get_qa_path,
    get_settings_path,
    get_smart_messaging_path,
    migrate_from_legacy,
)

__all__ = [
    "APP_SETTINGS_FILE",
    "APPOINTMENT_FINGERPRINTS_FILE",
    "CONTENT_DIR",
    "DAILY_TEMPLATE_DISPATCH_STATE_FILE",
    "DRY_RUN_MESSAGES_FILE",
    "KNOWLEDGE_BASE_FILE",
    "KNOWLEDGE_FILES_DIR",
    "MESSAGE_PREVIEW_QUEUE_FILE",
    "MESSAGE_QUEUE_FILE",
    "MESSAGE_TEMPLATES_FILE",
    "MESSAGE_TEMPLATES_LOCK_FILE",
    "PRICE_FILES_DIR",
    "PRICE_LIST_FILE",
    "QA_DATABASE_FILE",
    "QA_DIR",
    "QA_PAIRS_FILE",
    "SCHEDULED_MESSAGES_FILE",
    "SENT_SMART_MESSAGES_FILE",
    "SERVICE_TEMPLATE_MAPPING_FILE",
    "SETTINGS_DIR",
    "SMART_MESSAGING_DIR",
    "STYLE_FILES_DIR",
    "STYLE_GUIDE_FILE",
    "TEMPLATE_ACTIVATION_STATUS_FILE",
    "ensure_dirs",
    "get_content_path",
    "get_data_root",
    "get_qa_path",
    "get_settings_path",
    "get_smart_messaging_path",
    "migrate_from_legacy",
]
