# -*- coding: utf-8 -*-
"""Persistent storage paths and migration."""

from storage.persistent_storage import (
    get_data_root,
    get_qa_path,
    get_content_path,
    get_settings_path,
    get_smart_messaging_path,
    ensure_dirs,
    migrate_from_legacy,
    QA_DIR,
    QA_PAIRS_FILE,
    QA_DATABASE_FILE,
    CONTENT_DIR,
    SMART_MESSAGING_DIR,
    KNOWLEDGE_BASE_FILE,
    STYLE_GUIDE_FILE,
    PRICE_LIST_FILE,
    KNOWLEDGE_FILES_DIR,
    STYLE_FILES_DIR,
    PRICE_FILES_DIR,
    SETTINGS_DIR,
    APP_SETTINGS_FILE,
    SMART_MESSAGING_DIR,
    MESSAGE_TEMPLATES_FILE,
    MESSAGE_TEMPLATES_LOCK_FILE,
    SENT_SMART_MESSAGES_FILE,
    SERVICE_TEMPLATE_MAPPING_FILE,
    MESSAGE_PREVIEW_QUEUE_FILE,
    DAILY_TEMPLATE_DISPATCH_STATE_FILE,
    MESSAGE_QUEUE_FILE,
    APPOINTMENT_FINGERPRINTS_FILE,
    TEMPLATE_ACTIVATION_STATUS_FILE,
    SCHEDULED_MESSAGES_FILE,
    DRY_RUN_MESSAGES_FILE,
)
