/** Opening / splash screen design tokens — approved Linas AI cold-open spec. */

export const bootSplashTokens = {
  background: '#FBFAFA',
  glowColor: '#DFF4F1',
  glowOpacity: 0.38,
  glowBlurMin: 65,
  glowBlurMax: 85,
  sparkleColor: '#178F87',
  sparkleWidth: 68,
  sparkleHeight: 72,
  logoCenterYRatio: 0.47,
  onlineDotColor: '#20B2A6',
  onlineDotSize: 7,
  onlineDotGap: 8,
  appNameColor: '#0B0B0B',
  appNameSize: 27,
  appNameWeight: '600' as const,
  appNameLetterSpacing: -0.4,
  nameBelowLogo: 55,
  lineBelowName: 24,
  lineWidth: 94,
  lineHeight: 3,
  lineRadius: 2,
  lineTrackColor: '#D5EBE8',
  lineGradientStart: '#0B9C92',
  lineGradientMid: '#47C5BB',
  lineGlowColor: '#31B9AE',
  lineGlowOpacity: 0.3,
  lineGlowBlur: 7,
  lineSweepMs: 1250,
  linePulseMs: 900,
  linePulseMin: 0.65,
  linePulseMax: 1,
  lineSegmentWidth: 32,
  entranceOpacityMs: 280,
  entranceScaleMs: 320,
  entranceScaleFrom: 0.96,
  loadingDelayMs: 150,
  exitFadeMs: 220,
  minDisplayMs: 900,
  minDisplayReducedMs: 320,
} as const;
