"""ISO 639-1 world language catalog for Smart Q&A language picker."""

from __future__ import annotations

ISO639_LANGUAGES: tuple[tuple[str, str, str], ...] = (
    ("aa", "Afar", "Afar"),
    ("ab", "Abkhazian", "Аҧсуа"),
    ("ae", "Avestan", "Avesta"),
    ("af", "Afrikaans", "Afrikaans"),
    ("ak", "Akan", "Akan"),
    ("am", "Amharic", "አማርኛ"),
    ("an", "Aragonese", "Aragonés"),
    ("ar", "Arabic", "العربية"),
    ("as", "Assamese", "অসমীয়া"),
    ("av", "Avaric", "Авар"),
    ("ay", "Aymara", "Aymar"),
    ("az", "Azerbaijani", "Azərbaycan"),
    ("ba", "Bashkir", "Башҡорт"),
    ("be", "Belarusian", "Беларуская"),
    ("bg", "Bulgarian", "Български"),
    ("bh", "Bihari", "भोजपुरी"),
    ("bi", "Bislama", "Bislama"),
    ("bm", "Bambara", "Bamanankan"),
    ("bn", "Bengali", "বাংলা"),
    ("bo", "Tibetan", "བོད་ཡིག"),
    ("br", "Breton", "Brezhoneg"),
    ("bs", "Bosnian", "Bosanski"),
    ("ca", "Catalan", "Català"),
    ("ce", "Chechen", "Нохчийн"),
    ("ch", "Chamorro", "Chamoru"),
    ("co", "Corsican", "Corsu"),
    ("cr", "Cree", "ᓀᐦᐃᔭᐍᐏᐣ"),
    ("cs", "Czech", "Čeština"),
    ("cu", "Church Slavic", "Словѣньскъ"),
    ("cv", "Chuvash", "Чӑваш"),
    ("cy", "Welsh", "Cymraeg"),
    ("da", "Danish", "Dansk"),
    ("de", "German", "Deutsch"),
    ("dv", "Divehi", "ދިވެހި"),
    ("dz", "Dzongkha", "རྫོང་ཁ"),
    ("ee", "Ewe", "Eʋegbe"),
    ("el", "Greek", "Ελληνικά"),
    ("en", "English", "English"),
    ("eo", "Esperanto", "Esperanto"),
    ("es", "Spanish", "Español"),
    ("et", "Estonian", "Eesti"),
    ("eu", "Basque", "Euskara"),
    ("fa", "Persian", "فارسی"),
    ("ff", "Fulah", "Fulfulde"),
    ("fi", "Finnish", "Suomi"),
    ("fj", "Fijian", "Vosa Vakaviti"),
    ("fo", "Faroese", "Føroyskt"),
    ("fr", "French", "Français"),
    ("fy", "Western Frisian", "Frysk"),
    ("ga", "Irish", "Gaeilge"),
    ("gd", "Scottish Gaelic", "Gàidhlig"),
    ("gl", "Galician", "Galego"),
    ("gn", "Guarani", "Avañe'ẽ"),
    ("gu", "Gujarati", "ગુજરાતી"),
    ("gv", "Manx", "Gaelg"),
    ("ha", "Hausa", "Hausa"),
    ("he", "Hebrew", "עברית"),
    ("hi", "Hindi", "हिन्दी"),
    ("ho", "Hiri Motu", "Hiri Motu"),
    ("hr", "Croatian", "Hrvatski"),
    ("ht", "Haitian Creole", "Kreyòl ayisyen"),
    ("hu", "Hungarian", "Magyar"),
    ("hy", "Armenian", "Հայերեն"),
    ("hz", "Herero", "Otjiherero"),
    ("ia", "Interlingua", "Interlingua"),
    ("id", "Indonesian", "Bahasa Indonesia"),
    ("ie", "Interlingue", "Interlingue"),
    ("ig", "Igbo", "Igbo"),
    ("ii", "Sichuan Yi", "ꆈꌠꉙ"),
    ("ik", "Inupiaq", "Iñupiaq"),
    ("io", "Ido", "Ido"),
    ("is", "Icelandic", "Íslenska"),
    ("it", "Italian", "Italiano"),
    ("iu", "Inuktitut", "ᐃᓄᒃᑎᑐᑦ"),
    ("ja", "Japanese", "日本語"),
    ("jv", "Javanese", "Basa Jawa"),
    ("ka", "Georgian", "ქართული"),
    ("kg", "Kongo", "Kikongo"),
    ("ki", "Kikuyu", "Gĩkũyũ"),
    ("kj", "Kuanyama", "Kuanyama"),
    ("kk", "Kazakh", "Қазақ"),
    ("kl", "Kalaallisut", "Kalaallisut"),
    ("km", "Khmer", "ខ្មែរ"),
    ("kn", "Kannada", "ಕನ್ನಡ"),
    ("ko", "Korean", "한국어"),
    ("kr", "Kanuri", "Kanuri"),
    ("ks", "Kashmiri", "कश्मीरी"),
    ("ku", "Kurdish", "Kurdî"),
    ("kv", "Komi", "Коми"),
    ("kw", "Cornish", "Kernewek"),
    ("ky", "Kyrgyz", "Кыргызча"),
    ("la", "Latin", "Latina"),
    ("lb", "Luxembourgish", "Lëtzebuergesch"),
    ("lg", "Ganda", "Luganda"),
    ("li", "Limburgish", "Limburgs"),
    ("ln", "Lingala", "Lingála"),
    ("lo", "Lao", "ລາວ"),
    ("lt", "Lithuanian", "Lietuvių"),
    ("lu", "Luba-Katanga", "Tshiluba"),
    ("lv", "Latvian", "Latviešu"),
    ("mg", "Malagasy", "Malagasy"),
    ("mh", "Marshallese", "Kajin M̧ajeļ"),
    ("mi", "Māori", "Māori"),
    ("mk", "Macedonian", "Македонски"),
    ("ml", "Malayalam", "മലയാളം"),
    ("mn", "Mongolian", "Монгол"),
    ("mr", "Marathi", "मराठी"),
    ("ms", "Malay", "Bahasa Melayu"),
    ("mt", "Maltese", "Malti"),
    ("my", "Burmese", "မြန်မာ"),
    ("na", "Nauru", "Dorerin Naoero"),
    ("nb", "Norwegian Bokmål", "Norsk bokmål"),
    ("nd", "North Ndebele", "isiNdebele"),
    ("ne", "Nepali", "नेपाली"),
    ("ng", "Ndonga", "Owambo"),
    ("nl", "Dutch", "Nederlands"),
    ("nn", "Norwegian Nynorsk", "Norsk nynorsk"),
    ("no", "Norwegian", "Norsk"),
    ("nr", "South Ndebele", "isiNdebele"),
    ("nv", "Navajo", "Diné bizaad"),
    ("ny", "Chichewa", "Chichewa"),
    ("oc", "Occitan", "Occitan"),
    ("oj", "Ojibwa", "Anishinaabemowin"),
    ("om", "Oromo", "Oromoo"),
    ("or", "Odia", "ଓଡ଼ିଆ"),
    ("os", "Ossetian", "Ирон"),
    ("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    ("pi", "Pali", "Pāli"),
    ("pl", "Polish", "Polski"),
    ("ps", "Pashto", "پښتو"),
    ("pt", "Portuguese", "Português"),
    ("qu", "Quechua", "Runa Simi"),
    ("rm", "Romansh", "Rumantsch"),
    ("rn", "Rundi", "Ikirundi"),
    ("ro", "Romanian", "Română"),
    ("ru", "Russian", "Русский"),
    ("rw", "Kinyarwanda", "Kinyarwanda"),
    ("sa", "Sanskrit", "संस्कृतम्"),
    ("sc", "Sardinian", "Sardu"),
    ("sd", "Sindhi", "سنڌي"),
    ("se", "Northern Sami", "Davvisámegiella"),
    ("sg", "Sango", "Sängö"),
    ("si", "Sinhala", "සිංහල"),
    ("sk", "Slovak", "Slovenčina"),
    ("sl", "Slovenian", "Slovenščina"),
    ("sm", "Samoan", "Gagana Samoa"),
    ("sn", "Shona", "chiShona"),
    ("so", "Somali", "Soomaali"),
    ("sq", "Albanian", "Shqip"),
    ("sr", "Serbian", "Српски"),
    ("ss", "Swati", "SiSwati"),
    ("st", "Southern Sotho", "Sesotho"),
    ("su", "Sundanese", "Basa Sunda"),
    ("sv", "Swedish", "Svenska"),
    ("sw", "Swahili", "Kiswahili"),
    ("ta", "Tamil", "தமிழ்"),
    ("te", "Telugu", "తెలుగు"),
    ("tg", "Tajik", "Тоҷикӣ"),
    ("th", "Thai", "ไทย"),
    ("ti", "Tigrinya", "ትግርኛ"),
    ("tk", "Turkmen", "Türkmen"),
    ("tl", "Tagalog", "Tagalog"),
    ("tn", "Tswana", "Setswana"),
    ("to", "Tongan", "lea fakatonga"),
    ("tr", "Turkish", "Türkçe"),
    ("ts", "Tsonga", "Xitsonga"),
    ("tt", "Tatar", "Татар"),
    ("tw", "Twi", "Twi"),
    ("ty", "Tahitian", "Reo Tahiti"),
    ("ug", "Uyghur", "ئۇيغۇر"),
    ("uk", "Ukrainian", "Українська"),
    ("ur", "Urdu", "اردو"),
    ("uz", "Uzbek", "Oʻzbek"),
    ("ve", "Venda", "Tshivenḓa"),
    ("vi", "Vietnamese", "Tiếng Việt"),
    ("vo", "Volapük", "Volapük"),
    ("wa", "Walloon", "Walon"),
    ("wo", "Wolof", "Wolof"),
    ("xh", "Xhosa", "isiXhosa"),
    ("yi", "Yiddish", "ייִדיש"),
    ("yo", "Yoruba", "Yorùbá"),
    ("za", "Zhuang", "Vahcuengh"),
    ("zh", "Chinese", "中文"),
    ("zu", "Zulu", "isiZulu"),
    ("franco", "Franco / Arabizi", "Franco"),
)

_ISO639_BY_ID: dict[str, tuple[str, str, str]] = {row[0]: row for row in ISO639_LANGUAGES}

def iso639_catalog() -> list[dict[str, str]]:
    """Return catalog entries as {id, label, native} dicts."""
    return [{"id": code, "label": label, "native": native} for code, label, native in ISO639_LANGUAGES]

def iso639_label(code: str | None) -> str:
    row = _ISO639_BY_ID.get(str(code or "").strip().lower())
    return row[1] if row else str(code or "")

def iso639_native_label(code: str | None) -> str:
    row = _ISO639_BY_ID.get(str(code or "").strip().lower())
    return row[2] if row else iso639_label(code)

def is_valid_iso639_code(code: str | None) -> bool:
    return str(code or "").strip().lower() in _ISO639_BY_ID


_PRODUCT_ALIASES: dict[str, str] = {
    "arabic": "ar",
    "english": "en",
    "french": "fr",
    "franco-arabic": "franco",
    "franco_arabic": "franco",
    "arabizi": "franco",
    "spanish": "es",
    "german": "de",
    "italian": "it",
    "portuguese": "pt",
    "chinese": "zh",
    "turkish": "tr",
    "russian": "ru",
    "urdu": "ur",
    "punjabi": "pa",
    "hindi": "hi",
}


def normalize_language_code(code: str | None) -> str:
    raw = str(code or "").strip().lower().replace("_", "-")
    if not raw:
        return ""
    base = raw.split("-", 1)[0]
    raw = _PRODUCT_ALIASES.get(raw, _PRODUCT_ALIASES.get(base, base))
    return raw if is_valid_iso639_code(raw) else ""
