import { LANDING_ASSETS } from './landingDesignAssets';

export const HOW_IT_WORKS_HEADLINE = 'One app. Every step clear.';

export const HOW_IT_WORKS_STEPS = [
  {
    n: '01',
    kicker: 'OWNER COPILOT CHAT',
    title: 'Talk to Linas.',
    body: 'Tell Linas what changed. It updates the right business knowledge and confirms what was saved — no forms.',
    points: [
      { title: 'Tell Linas', body: 'Say what changed in your own words.' },
      { title: 'Confirm', body: 'See exactly what Linas understood.' },
      { title: 'Saved', body: 'Knowledge updates without a form.' },
    ],
    image: LANDING_ASSETS.tourScreens.ownerCopilot,
    alt: 'Owner Copilot chat in Linas AI',
  },
  {
    n: '02',
    kicker: 'SIDE MENU',
    title: 'Find everything fast.',
    body: 'Start a new chat, open any app section or return to recent conversations from one place.',
    points: [
      { title: 'Open', body: 'Jump to any part of the app.' },
      { title: 'Choose', body: 'Pick a section or a recent chat.' },
      { title: 'Continue', body: 'Pick up exactly where you left off.' },
    ],
    image: LANDING_ASSETS.tourScreens.sideMenu,
    alt: 'Linas AI side menu',
  },
  {
    n: '03',
    kicker: 'DASHBOARD',
    title: 'See what matters. Act faster.',
    body: 'Choose any date range to track credits, customer replies, requests, and channel performance—all in one clear view.',
    points: [
      { title: 'Choose dates', body: 'Pick the range that matters most.' },
      { title: 'Compare', body: 'Spot trends and measure progress.' },
      { title: 'Decide', body: 'Make confident decisions with a full picture.' },
    ],
    image: LANDING_ASSETS.tourScreens.dashboard,
    alt: 'Linas AI activity dashboard',
    builtScreen: 'dashboard',
  },
  {
    n: '04',
    kicker: 'AI SETUP',
    title: 'Teach every detail.',
    body: 'Review and edit the knowledge Linas uses: languages, tone, services, products, hours and policies.',
    points: [
      { title: 'Complete', body: 'Finish each setup section.' },
      { title: 'Review', body: 'Check what Linas will use.' },
      { title: 'Publish', body: 'Make the knowledge live.' },
    ],
    image: LANDING_ASSETS.tourScreens.aiSetup,
    alt: 'AI Setup progress in Linas AI',
  },
  {
    n: '05',
    kicker: 'SMART ANSWERS / Q&A',
    title: 'Save trusted answers.',
    body: 'Save trusted Q&A once, translate it to chosen languages and reuse it for similar questions to save credits.',
    points: [
      { title: 'Save once', body: 'Write the Q&A in your words.' },
      { title: 'Translate', body: 'It applies in every language you select.' },
      { title: 'Reuse', body: 'Matched replies cost 0 credits.' },
    ],
    image: LANDING_ASSETS.tourScreens.smartAnswers,
    alt: 'Smart Answers in Linas AI',
  },
  {
    n: '06',
    kicker: 'SMART FOLLOW-UP',
    title: 'Bring customers back.',
    body: 'Choose the channel, timing and goal. Linas follows up automatically when an interested customer goes quiet.',
    points: [
      { title: 'Goes quiet', body: 'Linas notices the pause.' },
      { title: 'Wait', body: 'Follow up on your timing.' },
      { title: 'Follow up', body: 'The conversation starts again.' },
    ],
    image: LANDING_ASSETS.tourScreens.smartFollowUp,
    alt: 'Smart Follow-Up settings',
  },
  {
    n: '07',
    kicker: 'INTEGRATIONS',
    title: 'Connect every channel.',
    body: 'Connect Instagram, Facebook, WhatsApp, TikTok and Web Chat, then control messages and comments.',
    points: [
      { title: 'Connect', body: 'Link each channel you use.' },
      { title: 'Verify', body: 'Confirm the account is ready.' },
      { title: 'Reply', body: 'Linas answers in that channel.' },
    ],
    image: LANDING_ASSETS.tourScreens.integrations,
    alt: 'Channel integrations in Linas AI',
  },
  {
    n: '08',
    kicker: 'LIVE CHAT CONVERSATION',
    title: 'Watch and take over.',
    body: 'See every conversation, take over from AI, assign a teammate and return the chat to AI without losing context.',
    points: [
      { title: 'AI replies', body: 'Linas handles the chat first.' },
      { title: 'Take over', body: 'Step in whenever you need.' },
      { title: 'Assign', body: 'Hand it to a teammate cleanly.' },
    ],
    image: LANDING_ASSETS.tourScreens.liveChat,
    alt: 'Live Chat takeover in Linas AI',
  },
  {
    n: '09',
    kicker: 'REQUESTS',
    title: 'Turn chats into work.',
    body: 'Turn orders, appointments and other requests into work you can assign, print and move from New to Done.',
    points: [
      { title: 'Capture', body: 'The request is saved from the chat.' },
      { title: 'Assign', body: 'Send it to the right person.' },
      { title: 'Complete', body: 'Move it from New to Done.' },
    ],
    image: LANDING_ASSETS.tourScreens.requests,
    alt: 'Requests board in Linas AI',
  },
  {
    n: '10',
    kicker: 'USERS & PERMISSIONS',
    title: 'Work as a team.',
    body: 'Add teammates, set roles and permissions, and decide exactly what each person can access.',
    points: [
      { title: 'Invite', body: 'Add the people who work with you.' },
      { title: 'Set access', body: 'Choose what each role can do.' },
      { title: 'Assign', body: 'Work stays in the right hands.' },
    ],
    image: LANDING_ASSETS.tourScreens.users,
    alt: 'Users and permissions in Linas AI',
  },
  {
    n: '11',
    kicker: 'SUBSCRIPTION & CREDITS',
    title: 'Control your capacity.',
    body: 'See your plan and credit balance, compare upgrades and buy extra credits when needed.',
    points: [
      { title: 'Check', body: 'See plan and credits remaining.' },
      { title: 'Compare', body: 'Look at the next plan clearly.' },
      { title: 'Upgrade', body: 'Add capacity when you need it.' },
    ],
    image: LANDING_ASSETS.tourScreens.subscription,
    alt: 'Subscription and credits in Linas AI',
  },
  {
    n: '12',
    kicker: 'CUSTOMER AI LIMITS',
    title: 'Protect your credits.',
    body: 'Set text, image, voice, daily, weekly and monthly limits to protect credits from unusually heavy use.',
    points: [
      { title: 'Set limit', body: 'Cap usage the way you want.' },
      { title: 'Monitor', body: 'See how customers use Linas.' },
      { title: 'Protect', body: 'Credits stay under your control.' },
    ],
    image: LANDING_ASSETS.tourScreens.aiLimits,
    alt: 'Customer AI Limits in Linas AI',
  },
  {
    n: '13',
    kicker: 'SETTINGS',
    title: 'Make the app yours.',
    body: 'Change your name, email, language, notifications, appearance and legal or account preferences.',
    points: [
      { title: 'Personalize', body: 'Set name, language and look.' },
      { title: 'Save', body: 'Keep the choices you made.' },
      { title: 'Sync', body: 'The app follows you everywhere.' },
    ],
    image: LANDING_ASSETS.tourScreens.settings,
    alt: 'Settings in Linas AI',
  },
];
