import { LANDING_ASSETS } from './landingDesignAssets';

export const HOW_IT_WORKS_STEPS = [
  {
    n: '01',
    kicker: 'OWNER COPILOT CHAT',
    title: 'Talk to Linas.',
    body: 'Tell Linas what changed. It updates the right business knowledge and confirms what was saved — no forms.',
    flow: ['Tell Linas', 'Confirm', 'Saved'],
    image: LANDING_ASSETS.tourScreens.ownerCopilot,
    alt: 'Owner Copilot chat in Linas AI',
  },
  {
    n: '02',
    kicker: 'SIDE MENU',
    title: 'Find everything fast.',
    body: 'Start a new chat, open any app section or return to recent conversations from one place.',
    flow: ['Open', 'Choose', 'Continue'],
    image: LANDING_ASSETS.tourScreens.sideMenu,
    alt: 'Linas AI side menu',
  },
  {
    n: '03',
    kicker: 'DASHBOARD',
    title: 'See what is happening.',
    body: 'See credits, replies, requests and channel performance for the date range you choose.',
    flow: ['Choose dates', 'Compare', 'Decide'],
    image: LANDING_ASSETS.tourScreens.dashboard,
    alt: 'Linas AI activity dashboard',
  },
  {
    n: '04',
    kicker: 'AI SETUP',
    title: 'Teach every detail.',
    body: 'Review and edit the knowledge Linas uses: languages, tone, services, products, hours and policies.',
    flow: ['Complete', 'Review', 'Publish'],
    image: LANDING_ASSETS.tourScreens.aiSetup,
    alt: 'AI Setup progress in Linas AI',
  },
  {
    n: '05',
    kicker: 'SMART ANSWERS / Q&A',
    title: 'Save trusted answers.',
    body: 'Save trusted Q&A once, translate it to chosen languages and reuse it for similar questions to save credits.',
    flow: ['Save once', 'Translate', 'Reuse'],
    image: LANDING_ASSETS.tourScreens.smartAnswers,
    alt: 'Smart Answers in Linas AI',
  },
  {
    n: '06',
    kicker: 'SMART FOLLOW-UP',
    title: 'Bring customers back.',
    body: 'Choose the channel, timing and goal. Linas follows up automatically when an interested customer goes quiet.',
    flow: ['Goes quiet', 'Wait', 'Follow up'],
    image: LANDING_ASSETS.tourScreens.smartFollowUp,
    alt: 'Smart Follow-Up settings',
  },
  {
    n: '07',
    kicker: 'INTEGRATIONS',
    title: 'Connect every channel.',
    body: 'Connect Instagram, Facebook, WhatsApp, TikTok and Web Chat, then control messages and comments.',
    flow: ['Connect', 'Verify', 'Reply'],
    image: LANDING_ASSETS.tourScreens.integrations,
    alt: 'Channel integrations in Linas AI',
  },
  {
    n: '08',
    kicker: 'LIVE CHAT CONVERSATION',
    title: 'Watch and take over.',
    body: 'See every conversation, take over from AI, assign a teammate and return the chat to AI without losing context.',
    flow: ['AI replies', 'Take over', 'Assign'],
    image: LANDING_ASSETS.tourScreens.liveChat,
    alt: 'Live Chat takeover in Linas AI',
  },
  {
    n: '09',
    kicker: 'REQUESTS',
    title: 'Turn chats into work.',
    body: 'Turn orders, appointments and other requests into work you can assign, print and move from New to Done.',
    flow: ['Capture', 'Assign', 'Complete'],
    image: LANDING_ASSETS.tourScreens.requests,
    alt: 'Requests board in Linas AI',
  },
  {
    n: '10',
    kicker: 'USERS & PERMISSIONS',
    title: 'Work as a team.',
    body: 'Add teammates, set roles and permissions, and decide exactly what each person can access.',
    flow: ['Invite', 'Set access', 'Assign'],
    image: LANDING_ASSETS.tourScreens.users,
    alt: 'Users and permissions in Linas AI',
  },
  {
    n: '11',
    kicker: 'SUBSCRIPTION & CREDITS',
    title: 'Control your capacity.',
    body: 'See your plan and credit balance, compare upgrades and buy extra credits when needed.',
    flow: ['Check', 'Compare', 'Upgrade'],
    image: LANDING_ASSETS.tourScreens.subscription,
    alt: 'Subscription and credits in Linas AI',
  },
  {
    n: '12',
    kicker: 'CUSTOMER AI LIMITS',
    title: 'Protect your credits.',
    body: 'Set text, image, voice, daily, weekly and monthly limits to protect credits from unusually heavy use.',
    flow: ['Set limit', 'Monitor', 'Protect'],
    image: LANDING_ASSETS.tourScreens.aiLimits,
    alt: 'Customer AI Limits in Linas AI',
  },
  {
    n: '13',
    kicker: 'SETTINGS',
    title: 'Make the app yours.',
    body: 'Change your name, email, language, notifications, appearance and legal or account preferences.',
    flow: ['Personalize', 'Save', 'Sync'],
    image: LANDING_ASSETS.tourScreens.settings,
    alt: 'Settings in Linas AI',
  },
];
