// Session role defaults used by resolveUserPermissions (login / verify-email).
export const SYSTEM_ROLES = {
  admin: {
    id: 'admin',
    name: 'Admin',
    description: 'Full access to all features',
    isSystem: true,
    permissions: {
      dashboard: true,
      liveChat: true,
      training: true,
      testing: true,
      analytics: true,
      smartMessaging: true,
      settings: true,
      userManagement: true,
      contentManagers: true,
      contentPublish: true,
      activityFlow: true,
      requests: true,
      requestsManage: true,
      requestsNotify: true,
      requestsManualChat: true,
      requestsSensitive: true,
      comments: true,
      commentsManage: true,
      channelWhatsapp: true,
      channelInstagram: true,
      channelFacebook: true,
      channelTiktok: true,
      channelWeb: true
    }
  },
  platform_owner: {
    id: 'platform_owner',
    name: 'Platform Owner',
    description: 'Linas AI platform operator (CLI-provisioned only; not assignable in-app)',
    isSystem: true,
    assignableInTenantUi: false,
    permissions: {
      dashboard: true,
      liveChat: true,
      training: true,
      testing: true,
      analytics: true,
      smartMessaging: true,
      settings: true,
      userManagement: true,
      contentManagers: true,
      contentPublish: true,
      activityFlow: true,
      requests: true,
      requestsManage: true,
      requestsNotify: true,
      requestsManualChat: true,
      requestsSensitive: true,
      comments: true,
      commentsManage: true,
      channelWhatsapp: true,
      channelInstagram: true,
      channelFacebook: true,
      channelTiktok: true,
      channelWeb: true
    }
  },
  operator: {
    id: 'operator',
    name: 'Operator',
    description: 'Can handle chats and view analytics',
    isSystem: true,
    permissions: {
      dashboard: true,
      liveChat: true,
      training: false,
      testing: false,
      analytics: true,
      smartMessaging: true,
      settings: false,
      userManagement: false,
      contentManagers: false,
      contentPublish: false,
      activityFlow: true,
      requests: true,
      requestsManage: true,
      requestsNotify: true,
      requestsManualChat: true,
      requestsSensitive: false,
      comments: true,
      commentsManage: true,
      channelWhatsapp: true,
      channelInstagram: true,
      channelFacebook: true,
      channelTiktok: true,
      channelWeb: true
    }
  },
  viewer: {
    id: 'viewer',
    name: 'Viewer',
    description: 'Read-only access to dashboard and history',
    isSystem: true,
    permissions: {
      dashboard: true,
      liveChat: false,
      training: false,
      testing: false,
      analytics: true,
      smartMessaging: false,
      settings: false,
      userManagement: false,
      contentManagers: false,
      contentPublish: false,
      activityFlow: true,
      requests: false,
      requestsManage: false,
      requestsNotify: false,
      requestsManualChat: false,
      requestsSensitive: false,
      comments: false,
      commentsManage: false,
      channelWhatsapp: true,
      channelInstagram: true,
      channelFacebook: true,
      channelTiktok: true,
      channelWeb: true
    }
  }
};

export const DEFAULT_PERMISSIONS = {
  dashboard: false,
  liveChat: false,
  training: false,
  testing: false,
  analytics: false,
  smartMessaging: false,
  settings: false,
  userManagement: false,
  contentManagers: false,
  contentPublish: false,
  activityFlow: false,
  requests: false,
  requestsManage: false,
  requestsNotify: false,
  requestsManualChat: false,
  requestsSensitive: false,
  comments: false,
  commentsManage: false,
  channelWhatsapp: true,
  channelInstagram: true,
  channelFacebook: true,
  channelTiktok: true,
  channelWeb: true
};

export const PERMISSION_KEYS = Object.keys(DEFAULT_PERMISSIONS);
