"""Canonical utils re-exports. Implementation lives in focused sibling modules."""

from __future__ import annotations

from utils.utils_context import (
    _filter_in_memory_context_for_window,
    append_turn_to_user_context_memory,
    get_conversation_context_for_gpt,
    get_conversation_history_from_firestore,
    get_conversation_last_ai_response_at,
    get_last_bot_message_for_gpt_context,
    get_last_bot_message_from_conversation,
)
from utils.utils_conversation_save import save_conversation_message_to_firestore
from utils.utils_firestore import get_firestore_db, initialize_firestore
from utils.utils_identity import (
    _clean_phone_for_lookup,
    _is_placeholder_phone,
    _load_room_to_phone_mapping,
    _normalize_phone_digits,
    _resolve_phone_from_room_mapping,
    get_canonical_user_id_and_phone,
    persist_room_to_phone_mapping,
)
from utils.utils_livechat_hooks import (
    MESSAGE_DEDUPE_WINDOW_SECONDS,
    _conversation_state_fields_changed,
    _ensure_live_chat_index_after_save,
    _extract_source_message_id,
    _invalidate_live_chat_cache,
    _is_duplicate_message,
    _latest_smart_ai_across_conversations,
    _message_to_dashboard_format,
    _parse_timestamp_for_dedupe,
    _propagate_takeover_state_to_sibling_conversation_docs,
    _refresh_live_chat_index_async,
    _resolve_conversation_doc_for_save,
    _resolve_latest_conversation_id,
    _update_customer_name_from_external_after_save,
)
from utils.utils_media import (
    convert_webm_to_opus,
    update_dashboard_metric_in_firestore,
    update_voice_message_with_transcription,
    upload_base64_to_firebase_storage,
)
from utils.utils_misc import (
    client,
    count_tokens,
    detect_language,
    notify_human_on_whatsapp,
    save_for_training_conversation_log,
    translate_qa_pair_with_gpt,
)
from utils.utils_prompt import get_system_instruction
from utils.utils_takeover import (
    _build_user_id_variants_for_release,
    _clear_takeover_flags_for_user,
    conversation_any_path_post_release_blocked,
    firestore_post_release_waiting_blocked,
    is_post_takeover_escalation_cooldown,
    iter_conversation_parent_user_ids_for_firestore,
    merge_conversation_user_id_variants,
    set_human_takeover_status,
    set_post_takeover_escalation_cooldown,
    sync_post_release_cooldown_from_conv_payload,
    update_conversation_on_all_existing_paths,
)
from utils.utils_tools import get_openai_tools_schema
from utils.utils_user_state import get_user_state_from_firestore, save_user_name_to_firestore

__all__ = [
    "MESSAGE_DEDUPE_WINDOW_SECONDS",
    "_build_user_id_variants_for_release",
    "_clean_phone_for_lookup",
    "_clear_takeover_flags_for_user",
    "_conversation_state_fields_changed",
    "_ensure_live_chat_index_after_save",
    "_extract_source_message_id",
    "_filter_in_memory_context_for_window",
    "_invalidate_live_chat_cache",
    "_is_duplicate_message",
    "_is_placeholder_phone",
    "_latest_smart_ai_across_conversations",
    "_load_room_to_phone_mapping",
    "_message_to_dashboard_format",
    "_normalize_phone_digits",
    "_parse_timestamp_for_dedupe",
    "_propagate_takeover_state_to_sibling_conversation_docs",
    "_refresh_live_chat_index_async",
    "_resolve_conversation_doc_for_save",
    "_resolve_latest_conversation_id",
    "_resolve_phone_from_room_mapping",
    "_update_customer_name_from_external_after_save",
    "append_turn_to_user_context_memory",
    "client",
    "conversation_any_path_post_release_blocked",
    "convert_webm_to_opus",
    "count_tokens",
    "detect_language",
    "firestore_post_release_waiting_blocked",
    "get_canonical_user_id_and_phone",
    "get_conversation_context_for_gpt",
    "get_conversation_history_from_firestore",
    "get_conversation_last_ai_response_at",
    "get_firestore_db",
    "get_last_bot_message_for_gpt_context",
    "get_last_bot_message_from_conversation",
    "get_openai_tools_schema",
    "get_system_instruction",
    "get_user_state_from_firestore",
    "initialize_firestore",
    "is_post_takeover_escalation_cooldown",
    "iter_conversation_parent_user_ids_for_firestore",
    "merge_conversation_user_id_variants",
    "notify_human_on_whatsapp",
    "persist_room_to_phone_mapping",
    "save_conversation_message_to_firestore",
    "save_for_training_conversation_log",
    "save_user_name_to_firestore",
    "set_human_takeover_status",
    "set_post_takeover_escalation_cooldown",
    "sync_post_release_cooldown_from_conv_payload",
    "translate_qa_pair_with_gpt",
    "update_conversation_on_all_existing_paths",
    "update_dashboard_metric_in_firestore",
    "update_voice_message_with_transcription",
    "upload_base64_to_firebase_storage",
]
