import { StyleSheet } from 'react-native';

import { fonts, spacing } from '../../../../theme';
import {
  locGreen,
  locGreenBg,
  locOrange,
  locRadius,
  locTeal,
  locTealSoft,
} from './locationHoursTokens';

export const locEditStyles = StyleSheet.create({
  published: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: locGreenBg,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  publishedText: {
    color: locGreen,
    fontFamily: fonts.bodyMedium,
    fontSize: 12,
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: locRadius,
    borderWidth: 1,
    borderColor: '#E4EEEC',
    padding: 4,
    marginBottom: spacing.md,
  },
  tab: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  tabOn: { backgroundColor: locTeal },
  tabText: {
    fontFamily: fonts.bodyMedium,
    fontSize: 15,
    color: '#10221A',
  },
  tabTextOn: { color: '#FFFFFF', fontWeight: '700' },
  fieldLabel: {
    color: '#5B6B6A',
    fontFamily: fonts.bodyMedium,
    fontSize: 13,
    marginBottom: 6,
  },
  mapWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D7E5E3',
    backgroundColor: '#F3F8F7',
    borderRadius: 14,
    marginBottom: spacing.md,
    paddingRight: 8,
  },
  mapInput: {
    flex: 1,
    color: '#10221A',
    fontFamily: fonts.body,
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  mapBtn: { padding: 8 },
  sectionTitle: {
    color: locTeal,
    fontFamily: fonts.bodyMedium,
    fontSize: 16,
    fontWeight: '700',
    marginTop: 4,
  },
  sectionHint: {
    color: '#8A9A98',
    fontFamily: fonts.body,
    fontSize: 13,
    marginTop: 4,
    marginBottom: spacing.md,
  },
  mediaActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: spacing.md,
  },
  mediaAction: { alignItems: 'center', gap: 6, minWidth: 64 },
  mediaActionLabel: {
    color: locTeal,
    fontFamily: fonts.bodyMedium,
    fontSize: 12,
  },
  mediaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E4EEEC',
    borderRadius: locRadius,
    padding: 10,
    marginBottom: 8,
  },
  mediaThumb: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: locTealSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaName: {
    color: '#10221A',
    fontFamily: fonts.bodyMedium,
    fontSize: 14,
  },
  mediaKind: {
    color: '#8A9A98',
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 2,
  },
  footer: {
    flexDirection: 'row',
    gap: 10,
    marginTop: spacing.md,
    marginBottom: spacing.xl,
  },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#DC2626',
    borderRadius: locRadius,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  deleteText: {
    color: '#DC2626',
    fontFamily: fonts.bodyMedium,
    fontSize: 16,
    fontWeight: '700',
  },
  saveBtn: {
    flex: 1,
    backgroundColor: locTeal,
    borderRadius: locRadius,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  saveText: {
    color: '#FFFFFF',
    fontFamily: fonts.bodyMedium,
    fontSize: 16,
    fontWeight: '700',
  },
  sameHours: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: locTealSoft,
    borderRadius: locRadius,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  sameHoursTitle: {
    color: locTeal,
    fontFamily: fonts.bodyMedium,
    fontSize: 14,
    fontWeight: '700',
  },
  sameHoursBody: {
    color: '#3A6F6A',
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 2,
  },
  outlineBtn: {
    borderWidth: 1,
    borderColor: locTeal,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  outlineBtnText: {
    color: locTeal,
    fontFamily: fonts.bodyMedium,
    fontSize: 12,
    fontWeight: '700',
  },
  weekBox: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E4EEEC',
    borderRadius: locRadius,
    overflow: 'hidden',
  },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF3F2',
    minHeight: 56,
  },
  dayName: {
    width: 78,
    color: '#10221A',
    fontFamily: fonts.bodyMedium,
    fontSize: 14,
  },
  timeBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D7E5E3',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: 'center',
  },
  timeText: {
    color: '#10221A',
    fontFamily: fonts.body,
    fontSize: 13,
    textAlign: 'center',
  },
  dash: { color: '#8A9A98', fontSize: 14 },
  openBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    minWidth: 62,
    justifyContent: 'flex-end',
  },
  openText: {
    color: locGreen,
    fontFamily: fonts.bodyMedium,
    fontSize: 14,
  },
  dayOffLabel: {
    flex: 1,
    color: locOrange,
    fontFamily: fonts.bodyMedium,
    fontSize: 14,
  },
  help: {
    color: '#8A9A98',
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 10,
    marginBottom: spacing.md,
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: '80%',
  },
  sheetTitle: {
    color: '#10221A',
    fontFamily: fonts.bodyMedium,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  dayChip: {
    borderWidth: 1,
    borderColor: '#D7E5E3',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  dayChipOn: {
    backgroundColor: locTealSoft,
    borderColor: locTeal,
  },
  error: {
    color: '#DC2626',
    fontFamily: fonts.body,
    fontSize: 13,
    marginBottom: 8,
  },
});
