import { StyleSheet } from 'react-native';

import { fonts, spacing } from '../../../../theme';
import { locDraftBg, locDraftText, locRadius, locTeal, locTealSoft } from './locationHoursTokens';

export const locListStyles = StyleSheet.create({
  addBtn: {
    backgroundColor: locTeal,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  addBtnText: {
    color: '#FFFFFF',
    fontFamily: fonts.bodyMedium,
    fontSize: 13,
    fontWeight: '700',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D7E5E3',
    backgroundColor: '#FFFFFF',
    borderRadius: locRadius,
    paddingHorizontal: 12,
    minHeight: 46,
    marginBottom: spacing.md,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: '#10221A',
    fontFamily: fonts.body,
    fontSize: 15,
    paddingVertical: 10,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: locRadius,
    borderWidth: 1,
    borderColor: '#E4EEEC',
    padding: spacing.md,
    marginBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pin: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: locTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1, minWidth: 0 },
  name: {
    color: '#10221A',
    fontFamily: fonts.bodyMedium,
    fontSize: 16,
    fontWeight: '700',
  },
  address: {
    color: '#5B6B6A',
    fontFamily: fonts.body,
    fontSize: 13,
    marginTop: 2,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  dot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { fontFamily: fonts.body, fontSize: 13 },
  draftBadge: {
    alignSelf: 'flex-start',
    marginTop: 6,
    backgroundColor: locDraftBg,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  draftText: {
    color: locDraftText,
    fontFamily: fonts.bodyMedium,
    fontSize: 11,
  },
  mediaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  mediaText: {
    color: '#8A9A98',
    fontFamily: fonts.body,
    fontSize: 12,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: locTealSoft,
    borderRadius: locRadius,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xl,
  },
  infoText: {
    flex: 1,
    color: '#145C56',
    fontFamily: fonts.body,
    fontSize: 13,
    lineHeight: 19,
  },
});
