/** Full ISO 639-1 (+ franco) catalog for Smart Q&A language picker. Keep in sync with services/cm/iso639_languages.py */

export type Iso639Lang = {
  id: string;
  label: string;
  native?: string;
};

export const ISO639_LANGUAGE_CATALOG: Iso639Lang[] = [
  { id: 'aa', label: 'Afar', native: 'Afar' },
  { id: 'ab', label: 'Abkhazian', native: 'Аҧсуа' },
  { id: 'ae', label: 'Avestan', native: 'Avesta' },
  { id: 'af', label: 'Afrikaans', native: 'Afrikaans' },
  { id: 'ak', label: 'Akan', native: 'Akan' },
  { id: 'am', label: 'Amharic', native: 'አማርኛ' },
  { id: 'an', label: 'Aragonese', native: 'Aragonés' },
  { id: 'ar', label: 'Arabic', native: 'العربية' },
  { id: 'as', label: 'Assamese', native: 'অসমীয়া' },
  { id: 'av', label: 'Avaric', native: 'Авар' },
  { id: 'ay', label: 'Aymara', native: 'Aymar' },
  { id: 'az', label: 'Azerbaijani', native: 'Azərbaycan' },
  { id: 'ba', label: 'Bashkir', native: 'Башҡорт' },
  { id: 'be', label: 'Belarusian', native: 'Беларуская' },
  { id: 'bg', label: 'Bulgarian', native: 'Български' },
  { id: 'bh', label: 'Bihari', native: 'भोजपुरी' },
  { id: 'bi', label: 'Bislama', native: 'Bislama' },
  { id: 'bm', label: 'Bambara', native: 'Bamanankan' },
  { id: 'bn', label: 'Bengali', native: 'বাংলা' },
  { id: 'bo', label: 'Tibetan', native: 'བོད་ཡིག' },
  { id: 'br', label: 'Breton', native: 'Brezhoneg' },
  { id: 'bs', label: 'Bosnian', native: 'Bosanski' },
  { id: 'ca', label: 'Catalan', native: 'Català' },
  { id: 'ce', label: 'Chechen', native: 'Нохчийн' },
  { id: 'ch', label: 'Chamorro', native: 'Chamoru' },
  { id: 'co', label: 'Corsican', native: 'Corsu' },
  { id: 'cr', label: 'Cree', native: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { id: 'cs', label: 'Czech', native: 'Čeština' },
  { id: 'cu', label: 'Church Slavic', native: 'Словѣньскъ' },
  { id: 'cv', label: 'Chuvash', native: 'Чӑваш' },
  { id: 'cy', label: 'Welsh', native: 'Cymraeg' },
  { id: 'da', label: 'Danish', native: 'Dansk' },
  { id: 'de', label: 'German', native: 'Deutsch' },
  { id: 'dv', label: 'Divehi', native: 'ދިވެހި' },
  { id: 'dz', label: 'Dzongkha', native: 'རྫོང་ཁ' },
  { id: 'ee', label: 'Ewe', native: 'Eʋegbe' },
  { id: 'el', label: 'Greek', native: 'Ελληνικά' },
  { id: 'en', label: 'English', native: 'English' },
  { id: 'eo', label: 'Esperanto', native: 'Esperanto' },
  { id: 'es', label: 'Spanish', native: 'Español' },
  { id: 'et', label: 'Estonian', native: 'Eesti' },
  { id: 'eu', label: 'Basque', native: 'Euskara' },
  { id: 'fa', label: 'Persian', native: 'فارسی' },
  { id: 'ff', label: 'Fulah', native: 'Fulfulde' },
  { id: 'fi', label: 'Finnish', native: 'Suomi' },
  { id: 'fj', label: 'Fijian', native: 'Vosa Vakaviti' },
  { id: 'fo', label: 'Faroese', native: 'Føroyskt' },
  { id: 'fr', label: 'French', native: 'Français' },
  { id: 'fy', label: 'Western Frisian', native: 'Frysk' },
  { id: 'ga', label: 'Irish', native: 'Gaeilge' },
  { id: 'gd', label: 'Scottish Gaelic', native: 'Gàidhlig' },
  { id: 'gl', label: 'Galician', native: 'Galego' },
  { id: 'gn', label: 'Guarani', native: 'Avañe\'ẽ' },
  { id: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
  { id: 'gv', label: 'Manx', native: 'Gaelg' },
  { id: 'ha', label: 'Hausa', native: 'Hausa' },
  { id: 'he', label: 'Hebrew', native: 'עברית' },
  { id: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { id: 'ho', label: 'Hiri Motu', native: 'Hiri Motu' },
  { id: 'hr', label: 'Croatian', native: 'Hrvatski' },
  { id: 'ht', label: 'Haitian Creole', native: 'Kreyòl ayisyen' },
  { id: 'hu', label: 'Hungarian', native: 'Magyar' },
  { id: 'hy', label: 'Armenian', native: 'Հայերեն' },
  { id: 'hz', label: 'Herero', native: 'Otjiherero' },
  { id: 'ia', label: 'Interlingua', native: 'Interlingua' },
  { id: 'id', label: 'Indonesian', native: 'Bahasa Indonesia' },
  { id: 'ie', label: 'Interlingue', native: 'Interlingue' },
  { id: 'ig', label: 'Igbo', native: 'Igbo' },
  { id: 'ii', label: 'Sichuan Yi', native: 'ꆈꌠꉙ' },
  { id: 'ik', label: 'Inupiaq', native: 'Iñupiaq' },
  { id: 'io', label: 'Ido', native: 'Ido' },
  { id: 'is', label: 'Icelandic', native: 'Íslenska' },
  { id: 'it', label: 'Italian', native: 'Italiano' },
  { id: 'iu', label: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ' },
  { id: 'ja', label: 'Japanese', native: '日本語' },
  { id: 'jv', label: 'Javanese', native: 'Basa Jawa' },
  { id: 'ka', label: 'Georgian', native: 'ქართული' },
  { id: 'kg', label: 'Kongo', native: 'Kikongo' },
  { id: 'ki', label: 'Kikuyu', native: 'Gĩkũyũ' },
  { id: 'kj', label: 'Kuanyama', native: 'Kuanyama' },
  { id: 'kk', label: 'Kazakh', native: 'Қазақ' },
  { id: 'kl', label: 'Kalaallisut', native: 'Kalaallisut' },
  { id: 'km', label: 'Khmer', native: 'ខ្មែរ' },
  { id: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { id: 'ko', label: 'Korean', native: '한국어' },
  { id: 'kr', label: 'Kanuri', native: 'Kanuri' },
  { id: 'ks', label: 'Kashmiri', native: 'कश्मीरी' },
  { id: 'ku', label: 'Kurdish', native: 'Kurdî' },
  { id: 'kv', label: 'Komi', native: 'Коми' },
  { id: 'kw', label: 'Cornish', native: 'Kernewek' },
  { id: 'ky', label: 'Kyrgyz', native: 'Кыргызча' },
  { id: 'la', label: 'Latin', native: 'Latina' },
  { id: 'lb', label: 'Luxembourgish', native: 'Lëtzebuergesch' },
  { id: 'lg', label: 'Ganda', native: 'Luganda' },
  { id: 'li', label: 'Limburgish', native: 'Limburgs' },
  { id: 'ln', label: 'Lingala', native: 'Lingála' },
  { id: 'lo', label: 'Lao', native: 'ລາວ' },
  { id: 'lt', label: 'Lithuanian', native: 'Lietuvių' },
  { id: 'lu', label: 'Luba-Katanga', native: 'Tshiluba' },
  { id: 'lv', label: 'Latvian', native: 'Latviešu' },
  { id: 'mg', label: 'Malagasy', native: 'Malagasy' },
  { id: 'mh', label: 'Marshallese', native: 'Kajin M̧ajeļ' },
  { id: 'mi', label: 'Māori', native: 'Māori' },
  { id: 'mk', label: 'Macedonian', native: 'Македонски' },
  { id: 'ml', label: 'Malayalam', native: 'മലയാളം' },
  { id: 'mn', label: 'Mongolian', native: 'Монгол' },
  { id: 'mr', label: 'Marathi', native: 'मराठी' },
  { id: 'ms', label: 'Malay', native: 'Bahasa Melayu' },
  { id: 'mt', label: 'Maltese', native: 'Malti' },
  { id: 'my', label: 'Burmese', native: 'မြန်မာ' },
  { id: 'na', label: 'Nauru', native: 'Dorerin Naoero' },
  { id: 'nb', label: 'Norwegian Bokmål', native: 'Norsk bokmål' },
  { id: 'nd', label: 'North Ndebele', native: 'isiNdebele' },
  { id: 'ne', label: 'Nepali', native: 'नेपाली' },
  { id: 'ng', label: 'Ndonga', native: 'Owambo' },
  { id: 'nl', label: 'Dutch', native: 'Nederlands' },
  { id: 'nn', label: 'Norwegian Nynorsk', native: 'Norsk nynorsk' },
  { id: 'no', label: 'Norwegian', native: 'Norsk' },
  { id: 'nr', label: 'South Ndebele', native: 'isiNdebele' },
  { id: 'nv', label: 'Navajo', native: 'Diné bizaad' },
  { id: 'ny', label: 'Chichewa', native: 'Chichewa' },
  { id: 'oc', label: 'Occitan', native: 'Occitan' },
  { id: 'oj', label: 'Ojibwa', native: 'Anishinaabemowin' },
  { id: 'om', label: 'Oromo', native: 'Oromoo' },
  { id: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' },
  { id: 'os', label: 'Ossetian', native: 'Ирон' },
  { id: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { id: 'pi', label: 'Pali', native: 'Pāli' },
  { id: 'pl', label: 'Polish', native: 'Polski' },
  { id: 'ps', label: 'Pashto', native: 'پښتو' },
  { id: 'pt', label: 'Portuguese', native: 'Português' },
  { id: 'qu', label: 'Quechua', native: 'Runa Simi' },
  { id: 'rm', label: 'Romansh', native: 'Rumantsch' },
  { id: 'rn', label: 'Rundi', native: 'Ikirundi' },
  { id: 'ro', label: 'Romanian', native: 'Română' },
  { id: 'ru', label: 'Russian', native: 'Русский' },
  { id: 'rw', label: 'Kinyarwanda', native: 'Kinyarwanda' },
  { id: 'sa', label: 'Sanskrit', native: 'संस्कृतम्' },
  { id: 'sc', label: 'Sardinian', native: 'Sardu' },
  { id: 'sd', label: 'Sindhi', native: 'سنڌي' },
  { id: 'se', label: 'Northern Sami', native: 'Davvisámegiella' },
  { id: 'sg', label: 'Sango', native: 'Sängö' },
  { id: 'si', label: 'Sinhala', native: 'සිංහල' },
  { id: 'sk', label: 'Slovak', native: 'Slovenčina' },
  { id: 'sl', label: 'Slovenian', native: 'Slovenščina' },
  { id: 'sm', label: 'Samoan', native: 'Gagana Samoa' },
  { id: 'sn', label: 'Shona', native: 'chiShona' },
  { id: 'so', label: 'Somali', native: 'Soomaali' },
  { id: 'sq', label: 'Albanian', native: 'Shqip' },
  { id: 'sr', label: 'Serbian', native: 'Српски' },
  { id: 'ss', label: 'Swati', native: 'SiSwati' },
  { id: 'st', label: 'Southern Sotho', native: 'Sesotho' },
  { id: 'su', label: 'Sundanese', native: 'Basa Sunda' },
  { id: 'sv', label: 'Swedish', native: 'Svenska' },
  { id: 'sw', label: 'Swahili', native: 'Kiswahili' },
  { id: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { id: 'te', label: 'Telugu', native: 'తెలుగు' },
  { id: 'tg', label: 'Tajik', native: 'Тоҷикӣ' },
  { id: 'th', label: 'Thai', native: 'ไทย' },
  { id: 'ti', label: 'Tigrinya', native: 'ትግርኛ' },
  { id: 'tk', label: 'Turkmen', native: 'Türkmen' },
  { id: 'tl', label: 'Tagalog', native: 'Tagalog' },
  { id: 'tn', label: 'Tswana', native: 'Setswana' },
  { id: 'to', label: 'Tongan', native: 'lea fakatonga' },
  { id: 'tr', label: 'Turkish', native: 'Türkçe' },
  { id: 'ts', label: 'Tsonga', native: 'Xitsonga' },
  { id: 'tt', label: 'Tatar', native: 'Татар' },
  { id: 'tw', label: 'Twi', native: 'Twi' },
  { id: 'ty', label: 'Tahitian', native: 'Reo Tahiti' },
  { id: 'ug', label: 'Uyghur', native: 'ئۇيغۇر' },
  { id: 'uk', label: 'Ukrainian', native: 'Українська' },
  { id: 'ur', label: 'Urdu', native: 'اردو' },
  { id: 'uz', label: 'Uzbek', native: 'Oʻzbek' },
  { id: 've', label: 'Venda', native: 'Tshivenḓa' },
  { id: 'vi', label: 'Vietnamese', native: 'Tiếng Việt' },
  { id: 'vo', label: 'Volapük', native: 'Volapük' },
  { id: 'wa', label: 'Walloon', native: 'Walon' },
  { id: 'wo', label: 'Wolof', native: 'Wolof' },
  { id: 'xh', label: 'Xhosa', native: 'isiXhosa' },
  { id: 'yi', label: 'Yiddish', native: 'ייִדיש' },
  { id: 'yo', label: 'Yoruba', native: 'Yorùbá' },
  { id: 'za', label: 'Zhuang', native: 'Vahcuengh' },
  { id: 'zh', label: 'Chinese', native: '中文' },
  { id: 'zu', label: 'Zulu', native: 'isiZulu' },
  { id: 'franco', label: 'Franco / Arabizi', native: 'Franco' },
];

